### ISSUE TITLE
Cannot Save

### ISSUE THREAD

**Issue by DepressionMain** [naturalcrit/homebrewery#1570]
Error: Service Unavailable

```
Error: Service Unavailable
    at Request.<anonymous> (https://homebrewery.naturalcrit.com/homebrew/bundle.js:71831:19)
    at Request.Emitter.emit (https://homebrewery.naturalcrit.com/homebrew/bundle.js:1764:20)
    at XMLHttpRequest.xhr.onreadystatechange (https://homebrewery.naturalcrit.com/homebrew/bundle.js:72140:10)
{
  "status": 503,
  "method": "POST",
  "url": "/api/newGoogle/"
}
```

**Comment by Gazook89** [comment]
Try this: 

1. Go to https://www.naturalcrit.com/login and logout (link at bottom of page)
2. Log back in using Google credentials

Let us know if that works

**Comment by Gazook89** [comment]
closing as duplicate:  #1580
