### ISSUE TITLE
Unable to save

### ISSUE THREAD

**Issue by onionchilde** [naturalcrit/homebrewery#1582]
Error: Service Unavailable

```
Error: Service Unavailable
    at Request.<anonymous> (https://homebrewery.naturalcrit.com/homebrew/bundle.js:71831:19)
    at Request.Emitter.emit (https://homebrewery.naturalcrit.com/homebrew/bundle.js:1764:20)
    at XMLHttpRequest.xhr.onreadystatechange (https://homebrewery.naturalcrit.com/homebrew/bundle.js:72140:10)
{
  "status": 503,
  "method": "POST",
  "url": "/api/newGoogle/"
}
```

**Comment by Gazook89** [comment]
See response here: https://github.com/naturalcrit/homebrewery/issues/1559#issuecomment-899856546

**Comment by Gazook89** [comment]
Closing as duplicate.  Discussion here: #1580
