### ISSUE TITLE
Not letting me save my work

### ISSUE THREAD

**Issue by Samsational** [naturalcrit/homebrewery#1615]
Error: Service Unavailable

```
Error: Service Unavailable
    at Request.<anonymous> (https://homebrewery.naturalcrit.com/homebrew/bundle.js:71831:19)
    at Request.Emitter.emit (https://homebrewery.naturalcrit.com/homebrew/bundle.js:1764:20)
    at XMLHttpRequest.xhr.onreadystatechange (https://homebrewery.naturalcrit.com/homebrew/bundle.js:72140:10)
{
  "status": 503,
  "method": "POST",
  "url": "/api/newGoogle/"
}
```

**Comment by Gazook89** [comment]
See discussion #1580 for a solution.  Will close this as a duplicate issue, but let us know if still having issues after checking out that thread and this can be re-opened.
