### ISSUE TITLE
Saving and Publishing issues

### ISSUE THREAD

**Issue by SoleilSiralos** [naturalcrit/homebrewery#1628]
Error: Service Unavailable
Hi! Unfortunately I'm having problems saving items on my homebrew and am unable to publish it

```
Error: Service Unavailable
    at Request.<anonymous> (https://homebrewery.naturalcrit.com/homebrew/bundle.js:71831:19)
    at Request.Emitter.emit (https://homebrewery.naturalcrit.com/homebrew/bundle.js:1764:20)
    at XMLHttpRequest.xhr.onreadystatechange (https://homebrewery.naturalcrit.com/homebrew/bundle.js:72140:10)
{
  "status": 503,
  "method": "POST",
  "url": "/api/newGoogle/"
}
```

**Comment by calculuschild** [comment]
Take a look at #1580 for the most likely solution. There have been some recent issues with Google credentials expiring and that is most likely the case here. If that doesn't help, feel free to reopen this issue @SoleilSiralos .
