### ISSUE TITLE
Save Error - Issue Report

### ISSUE THREAD

**Issue by Murdoc14** [naturalcrit/homebrewery#1633]
Error: Service Unavailable

```
Error: Service Unavailable
    at Request.<anonymous> (https://homebrewery.naturalcrit.com/homebrew/bundle.js:71831:19)
    at Request.Emitter.emit (https://homebrewery.naturalcrit.com/homebrew/bundle.js:1764:20)
    at XMLHttpRequest.xhr.onreadystatechange (https://homebrewery.naturalcrit.com/homebrew/bundle.js:72140:10)
{
  "status": 503,
  "method": "PUT",
  "url": "/api/updateGoogle/068eIRc6_tsD"
}
```

**Comment by Gazook89** [comment]
See discussion #1580 for a solution. Let us know if that doesn't fix it

**Comment by Gazook89** [comment]
Closing as a duplicate, it can be re-opened if the steps in #1580 don't fix the issue.
