### ISSUE TITLE
Save not working after Google Drive sign-in

### ISSUE THREAD

**Issue by RockyBadlands** [naturalcrit/homebrewery#1637]
Error: Service Unavailable

```
Error: Service Unavailable
    at Request.<anonymous> (https://homebrewery.naturalcrit.com/homebrew/bundle.js:71831:19)
    at Request.Emitter.emit (https://homebrewery.naturalcrit.com/homebrew/bundle.js:1764:20)
    at XMLHttpRequest.xhr.onreadystatechange (https://homebrewery.naturalcrit.com/homebrew/bundle.js:72140:10)
{
  "status": 503,
  "method": "POST",
  "url": "/api/newGoogle/"
}
```

**Comment by calculuschild** [comment]
See discussion #1580 for a solution. Let us know if that doesn't fix it. Will close as a duplicate but can be reopened if needed.
