### ISSUE TITLE
Issue Saving

### ISSUE THREAD

**Issue by Stathoua** [naturalcrit/homebrewery#1638]
Error: Service Unavailable

```
Error: Service Unavailable
    at Request.<anonymous> (https://homebrewery.naturalcrit.com/homebrew/bundle.js:71831:19)
    at Request.Emitter.emit (https://homebrewery.naturalcrit.com/homebrew/bundle.js:1764:20)
    at XMLHttpRequest.xhr.onreadystatechange (https://homebrewery.naturalcrit.com/homebrew/bundle.js:72140:10)
{
  "status": 503,
  "method": "PUT",
  "url": "/api/update/9Dhh3Q-m7Ks2"
}
```

**Comment by calculuschild** [comment]
Take a look at the help info in discussion #1580 -- if that doesn't do it for you, come back here and the issue can be re-opened. For now, closing as duplicate.
