### ISSUE TITLE
Error Saving

### ISSUE THREAD

**Issue by GDowling1** [naturalcrit/homebrewery#1653]
Error: Service Unavailable

```
Error: Service Unavailable
    at Request.<anonymous> (https://homebrewery.naturalcrit.com/homebrew/bundle.js:71831:19)
    at Request.Emitter.emit (https://homebrewery.naturalcrit.com/homebrew/bundle.js:1764:20)
    at XMLHttpRequest.xhr.onreadystatechange (https://homebrewery.naturalcrit.com/homebrew/bundle.js:72140:10)
{
  "status": 503,
  "method": "POST",
  "url": "/api/newGoogle/"
}
```

I have followed the instructions from discussion #1580 - as I have seen it suggested for a number of others, unfortunately the issue is still persisting.

Any other solutions available? 

Thanks.

**Comment by calculuschild** [comment]
If you feel comfortable sharing your username I can give your account a look and see if something's stuck.

**Comment by GDowling1** [comment]
Sure, its just 'GDowling'.

**Comment by GDowling1** [comment]
After some more trying it seems to be working now. So no need to look into it, cheers.
