### ISSUE TITLE
Homebrewery Won't Save New Document

### ISSUE THREAD

**Issue by bvande01** [naturalcrit/homebrewery#1654]
Error: Service Unavailable

```
Error: Service Unavailable
    at Request.<anonymous> (https://homebrewery.naturalcrit.com/homebrew/bundle.js:71831:19)
    at Request.Emitter.emit (https://homebrewery.naturalcrit.com/homebrew/bundle.js:1764:20)
    at XMLHttpRequest.xhr.onreadystatechange (https://homebrewery.naturalcrit.com/homebrew/bundle.js:72140:10)
{
  "status": 503,
  "method": "POST",
  "url": "/api/newGoogle/"
}
```
![Screenshot 2021-09-09 113230](https://user-images.githubusercontent.com/73769839/132716544-233210aa-157c-47ab-9900-239cb886ce2e.png)

**Comment by calculuschild** [comment]
Take a look at the help info in discussion #1580 -- if that doesn't do it for you, come back here and the issue can be re-opened. For now, closing as duplicate.
