### ISSUE TITLE
Homebrewery Save/Application Error

### ISSUE THREAD

**Issue by SylusElliot** [naturalcrit/homebrewery#1657]
Error: Service Unavailable

```
Error: Service Unavailable
    at Request.<anonymous> (https://homebrewery.naturalcrit.com/homebrew/bundle.js:71831:19)
    at Request.Emitter.emit (https://homebrewery.naturalcrit.com/homebrew/bundle.js:1764:20)
    at XMLHttpRequest.xhr.onreadystatechange (https://homebrewery.naturalcrit.com/homebrew/bundle.js:72140:10)
{
  "status": 503,
  "method": "PUT",
  "url": "/api/update/3Xc1p0vHE0tf"
}
```

**Comment by calculuschild** [comment]
The site had an outage for a couple of minutes right around that time. It should be working for you now. Closing, but can be reopened if it's still not working for you.
