### ISSUE TITLE
I can't save the document, i guess?

### ISSUE THREAD

**Issue by DrPlumcake** [naturalcrit/homebrewery#1677]
Error: Service Unavailable

```
Error: Service Unavailable
    at Request.<anonymous> (https://homebrewery.naturalcrit.com/homebrew/bundle.js:71824:19)
    at Request.Emitter.emit (https://homebrewery.naturalcrit.com/homebrew/bundle.js:1764:20)
    at XMLHttpRequest.xhr.onreadystatechange (https://homebrewery.naturalcrit.com/homebrew/bundle.js:72133:10)
{
  "status": 503,
  "method": "PUT",
  "url": "/api/updateGoogle/rgFuGLh3ZEu1"
}
```

**Comment by calculuschild** [comment]
@DrPlumcake  Give it another try. We just had a momentary hiccup on the server but It should be back already.

**Comment by calculuschild** [comment]
Closing since there hasn't been a reply from the user for a while and it is assumed the problem was solved.

If you are still experiencing this issue, feel free to reopen and provide information, @DrPlumcake
