### ISSUE TITLE
Unable to save

### ISSUE THREAD

**Issue by Taiyoukoio** [naturalcrit/homebrewery#1692]
Error: Bad Request

```
Error: Bad Request
    at Request.<anonymous> (https://homebrewery.naturalcrit.com/homebrew/bundle.js:71824:19)
    at Request.Emitter.emit (https://homebrewery.naturalcrit.com/homebrew/bundle.js:1764:20)
    at XMLHttpRequest.xhr.onreadystatechange (https://homebrewery.naturalcrit.com/homebrew/bundle.js:72133:10)
{
  "status": 400,
  "method": "POST",
  "url": "/api/newGoogle/"
}
```

**Comment by Gazook89** [comment]
@Taiyoukoio are you still having issues with this? Sorry for delayed response-- if still running into this issue, checkout discussion #1580 and see if the steps there don't help. Going to close this for now as a duplicate but it can be reopened if the problem persists.
