### ISSUE TITLE
Unsure issue, now prevents entering the site. Application error.

### ISSUE THREAD

**Issue by MrBeardie** [naturalcrit/homebrewery#1694]
Error: Service Unavailable

```
Error: Service Unavailable
    at Request.<anonymous> (https://homebrewery.naturalcrit.com/homebrew/bundle.js:71824:19)
    at Request.Emitter.emit (https://homebrewery.naturalcrit.com/homebrew/bundle.js:1764:20)
    at XMLHttpRequest.xhr.onreadystatechange (https://homebrewery.naturalcrit.com/homebrew/bundle.js:72133:10)
{
  "status": 503,
  "method": "PUT",
  "url": "/api/update/zlzVHocHi1U4"
}
```

**Comment by calculuschild** [comment]
Give it another try in a couple of minutes. Had a small hiccup on the server.
