### ISSUE TITLE
Not Properly saving????

### ISSUE THREAD

**Issue by Armasminecraft** [naturalcrit/homebrewery#1700]
Error: Service Unavailable

```
Error: Service Unavailable
    at Request.<anonymous> (https://homebrewery.naturalcrit.com/homebrew/bundle.js:71824:19)
    at Request.Emitter.emit (https://homebrewery.naturalcrit.com/homebrew/bundle.js:1764:20)
    at XMLHttpRequest.xhr.onreadystatechange (https://homebrewery.naturalcrit.com/homebrew/bundle.js:72133:10)
{
  "status": 503,
  "method": "PUT",
  "url": "/api/update/uz46sv7vV4oy"
}
```

**Comment by Gazook89** [comment]
Check out the discussion at #1580 and see if that helps.  Going to close this as a duplicate for now, but let us know if the steps in #1580 don't resolve your issue and we can reopen this issue.

**Comment by Armasminecraft** [comment]
honestly i didnt do what you said, it just started working
thank you for the advice though! 
it was a big scare to see my work wasn't being saved....
