### ISSUE TITLE
Trying to save just a basic page, doesn't work.

### ISSUE THREAD

**Issue by perkettratwit** [naturalcrit/homebrewery#1708]
Error: Bad Request

```
Error: Bad Request
    at Request.<anonymous> (https://homebrewery.naturalcrit.com/homebrew/bundle.js:71824:19)
    at Request.Emitter.emit (https://homebrewery.naturalcrit.com/homebrew/bundle.js:1764:20)
    at XMLHttpRequest.xhr.onreadystatechange (https://homebrewery.naturalcrit.com/homebrew/bundle.js:72133:10)
{
  "status": 400,
  "method": "POST",
  "url": "/api/newGoogle/"
}
```

**Comment by Gazook89** [comment]
Check out discussion #1580 to reset your google credentials.  If the steps there don't help, come back here and let us know but otherwise going to close this Issue in the meantime.  Thanks for the report
