### ISSUE TITLE
Continued issues saving

### ISSUE THREAD

**Issue by perkettratwit** [naturalcrit/homebrewery#1709]
Hello! I tried resetting my google credentials, as requested, and it has not solved my problem. It gave me this instead.
![image](https://user-images.githubusercontent.com/71512563/134402682-6d4ec48e-ee0b-4517-b46d-833576f1419d.png)

Anywho, here's the error information.

Error: Bad Request

```
Error: Bad Request
    at Request.<anonymous> (https://homebrewery.naturalcrit.com/homebrew/bundle.js:71824:19)
    at Request.Emitter.emit (https://homebrewery.naturalcrit.com/homebrew/bundle.js:1764:20)
    at XMLHttpRequest.xhr.onreadystatechange (https://homebrewery.naturalcrit.com/homebrew/bundle.js:72133:10)
{
  "status": 400,
  "method": "POST",
  "url": "/api/newGoogle/"
}
```

**Comment by perkettratwit** [comment]
I did - however, I just solved this myself by using a different account. Seems to be working now.
