### ISSUE TITLE
Cannot Save Brew

### ISSUE THREAD

**Issue by elpengwino** [naturalcrit/homebrewery#1712]
I attempted to save a brew containing only a wide monster stat block. The error prompt said only "looks like there was a problem saving" and directed me here to report the issue. It would not allow me to retry the save action.

Error: Bad Request

```
Error: Bad Request
    at Request.<anonymous> (https://homebrewery.naturalcrit.com/homebrew/bundle.js:71824:19)
    at Request.Emitter.emit (https://homebrewery.naturalcrit.com/homebrew/bundle.js:1764:20)
    at XMLHttpRequest.xhr.onreadystatechange (https://homebrewery.naturalcrit.com/homebrew/bundle.js:72133:10)
{
  "status": 400,
  "method": "POST",
  "url": "/api/newGoogle/"
}
```

**Comment by Gazook89** [comment]
Checkout discussion #1580 here on GitHub and see if following this steps fixes it

**Comment by Gazook89** [comment]
going to close this as a duplicate-- if the steps in #1580 haven't helped get your google credentials reset then come back here and we can re-open the Issue and see else needs to be done.  Thanks for the report!
