### ISSUE TITLE
Save Not Working

### ISSUE THREAD

**Issue by Sylvalis** [naturalcrit/homebrewery#1723]
Error: Service Unavailable

```
Error: Service Unavailable
    at Request.<anonymous> (https://homebrewery.naturalcrit.com/homebrew/bundle.js:71824:19)
    at Request.Emitter.emit (https://homebrewery.naturalcrit.com/homebrew/bundle.js:1764:20)
    at XMLHttpRequest.xhr.onreadystatechange (https://homebrewery.naturalcrit.com/homebrew/bundle.js:72133:10)
{
  "status": 503,
  "method": "PUT",
  "url": "/api/updateGoogle/mTieLoZq6eUi"
}
```

**Comment by G-Ambatte** [comment]
Try following the steps in #1580 - this should resolve your issues. If you continue to experience this problem, please re-open this issue.
