### ISSUE TITLE
can't save

### ISSUE THREAD

**Issue by JustAnotherStory** [naturalcrit/homebrewery#1725]
Error: Bad Request

```
Error: Bad Request
    at Request.<anonymous> (https://homebrewery.naturalcrit.com/homebrew/bundle.js:71824:19)
    at Request.Emitter.emit (https://homebrewery.naturalcrit.com/homebrew/bundle.js:1764:20)
    at XMLHttpRequest.xhr.onreadystatechange (https://homebrewery.naturalcrit.com/homebrew/bundle.js:72133:10)
{
  "status": 400,
  "method": "POST",
  "url": "/api/newGoogle/"
}
```

**Comment by G-Ambatte** [comment]
Try following the steps in #1580 - this should resolve your issues. If you continue to experience this problem, please let us know and we will re-open this issue for further investigation.
