### ISSUE TITLE
i got an ussue, heads up

### ISSUE THREAD

**Issue by lesttest** [naturalcrit/homebrewery#1730]
Error: Service Unavailable

```
Error: Service Unavailable
    at Request.<anonymous> (https://homebrewery.naturalcrit.com/homebrew/bundle.js:71824:19)
    at Request.Emitter.emit (https://homebrewery.naturalcrit.com/homebrew/bundle.js:1764:20)
    at XMLHttpRequest.xhr.onreadystatechange (https://homebrewery.naturalcrit.com/homebrew/bundle.js:72133:10)
{
  "status": 503,
  "method": "PUT",
  "url": "/api/updateGoogle/jnVzLrEM_ZHE"
}
```

**Comment by Gazook89** [comment]
Check out the steps outlined in discussion #1580 about re-authorizing your google account.  Will close this issue for now, but if those steps do not work this issue can be reopened to take a second look.
