### ISSUE TITLE
Wont save

### ISSUE THREAD

**Issue by bigmandiaphram** [naturalcrit/homebrewery#1734]
Error: Bad Request

```
Error: Bad Request
    at Request.<anonymous> (https://homebrewery.naturalcrit.com/homebrew/bundle.js:71824:19)
    at Request.Emitter.emit (https://homebrewery.naturalcrit.com/homebrew/bundle.js:1764:20)
    at XMLHttpRequest.xhr.onreadystatechange (https://homebrewery.naturalcrit.com/homebrew/bundle.js:72133:10)
{
  "status": 400,
  "method": "POST",
  "url": "/api/newGoogle/"
}
```

**Comment by Gazook89** [comment]
I'm sorry this didn't get a response before now-- if you are still having an issue saving it likely means your brew is saved to your Google account, and your google credentials need to be refreshed with Homebrewery.  Check out the steps in discussion #1580 and that should take care of it.  

Going to close this issue for now, but if those steps don't help let us know here and we can dig deeper.
