### ISSUE TITLE
a

### ISSUE THREAD

**Issue by VGH15** [naturalcrit/homebrewery#1762]
Error: Bad Request

```
Error: Bad Request
    at Request.<anonymous> (https://homebrewery.naturalcrit.com/homebrew/bundle.js:71844:19)
    at Request.Emitter.emit (https://homebrewery.naturalcrit.com/homebrew/bundle.js:1768:20)
    at XMLHttpRequest.xhr.onreadystatechange (https://homebrewery.naturalcrit.com/homebrew/bundle.js:72153:10)
{
  "status": 400,
  "method": "POST",
  "url": "/api/newGoogle/"
}
```

**Comment by calculuschild** [comment]
Try following the steps in #1580 - this should resolve your issues. If you continue to experience this problem, please let us know and we will re-open this issue for further investigation.
