### ISSUE TITLE
What is the problem here? I cannot save new brews, I can save only the old ones...

### ISSUE THREAD

**Issue by scola01** [naturalcrit/homebrewery#1764]
Error: Forbidden

```
Error: Forbidden
    at Request.<anonymous> (https://homebrewery.naturalcrit.com/homebrew/bundle.js:71844:19)
    at Request.Emitter.emit (https://homebrewery.naturalcrit.com/homebrew/bundle.js:1768:20)
    at XMLHttpRequest.xhr.onreadystatechange (https://homebrewery.naturalcrit.com/homebrew/bundle.js:72153:10)
{
  "status": 403,
  "method": "POST",
  "url": "/api/newGoogle/"
}
```

**Comment by calculuschild** [comment]
Try following the steps in #1580 - this should resolve your issues. If you continue to experience this problem, please let us know and we will re-open this issue for further investigation.
