### ISSUE TITLE
Brew not saving

### ISSUE THREAD

**Issue by homerisms** [naturalcrit/homebrewery#1823]
Error: Bad Request

```
Error: Bad Request
    at Request.<anonymous> (https://homebrewery.naturalcrit.com/homebrew/bundle.js:71842:19)
    at Request.Emitter.emit (https://homebrewery.naturalcrit.com/homebrew/bundle.js:1768:20)
    at XMLHttpRequest.xhr.onreadystatechange (https://homebrewery.naturalcrit.com/homebrew/bundle.js:72151:10)
{
  "status": 400,
  "method": "POST",
  "url": "/api/newGoogle/"
}
```

**Comment by Gazook89** [comment]
Check out Steps in discussion #1580

**Comment by Gazook89** [comment]
Going to close this for now, but if the steps in #1580 don't fix the issue we can reopen it.
