### ISSUE TITLE
Error on Homebrewery. Got directed here.

### ISSUE THREAD

**Issue by jaspertjong** [naturalcrit/homebrewery#1824]
Error: Bad Request

```
Error: Bad Request
    at Request.<anonymous> (https://homebrewery.naturalcrit.com/homebrew/bundle.js:71842:19)
    at Request.Emitter.emit (https://homebrewery.naturalcrit.com/homebrew/bundle.js:1768:20)
    at XMLHttpRequest.xhr.onreadystatechange (https://homebrewery.naturalcrit.com/homebrew/bundle.js:72151:10)
{
  "status": 400,
  "method": "POST",
  "url": "/api/newGoogle/"
}
```

**Comment by Gazook89** [comment]
Check out the steps in discussion #1580 for resolving this.  Will close this Issue for now, but it can be reopened if those steps don't work for you.
