### ISSUE TITLE
unable to save

### ISSUE THREAD

**Issue by lukedesmith** [naturalcrit/homebrewery#1826]
Error: Bad Request

```
Error: Bad Request
    at Request.<anonymous> (https://homebrewery.naturalcrit.com/homebrew/bundle.js:71842:19)
    at Request.Emitter.emit (https://homebrewery.naturalcrit.com/homebrew/bundle.js:1768:20)
    at XMLHttpRequest.xhr.onreadystatechange (https://homebrewery.naturalcrit.com/homebrew/bundle.js:72151:10)
{
  "status": 400,
  "method": "POST",
  "url": "/api/newGoogle/"
}
```

**Comment by Gazook89** [comment]
Checkout the steps posted in Discussion #1580 to resolve expired google credentials.  Going to close this issue for now, but if those steps don't help come back here and this can be re-opened and next steps taken.
