### ISSUE TITLE
Can't Save 

### ISSUE THREAD

**Issue by Dahoshivik** [naturalcrit/homebrewery#1837]
Error: Bad Request

```
Error: Bad Request
    at Request.<anonymous> (https://homebrewery.naturalcrit.com/homebrew/bundle.js:72168:19)
    at Request.Emitter.emit (https://homebrewery.naturalcrit.com/homebrew/bundle.js:1768:20)
    at XMLHttpRequest.xhr.onreadystatechange (https://homebrewery.naturalcrit.com/homebrew/bundle.js:72477:10)
{
  "status": 400,
  "method": "POST",
  "url": "/api/newGoogle/"
}
```

**Comment by Gazook89** [comment]
Check out the steps in discussion #1580 and those should help you out.  Going to close this issue but it can be reopened if those steps don't help.
