### ISSUE TITLE
I cant save the thing help

### ISSUE THREAD

**Issue by BUISNESS-JAI-OF-BUISNESS-STREET** [naturalcrit/homebrewery#1859]
Error: Bad Request

```
Error: Bad Request
    at Request.<anonymous> (https://homebrewery.naturalcrit.com/homebrew/bundle.js:72168:19)
    at Request.Emitter.emit (https://homebrewery.naturalcrit.com/homebrew/bundle.js:1768:20)
    at XMLHttpRequest.xhr.onreadystatechange (https://homebrewery.naturalcrit.com/homebrew/bundle.js:72477:10)
{
  "status": 400,
  "method": "POST",
  "url": "/api/newGoogle/"
}
```

**Comment by calculuschild** [comment]
This is a pretty common issue and just means your Google credentials have expired and you need to sign in again. Check #1580 for detailed steps.

I'm going to close this, but if you still have issues after following those steps let us know here and we can open it back up.
