### ISSUE TITLE
Wont save

### ISSUE THREAD

**Issue by ReformedPastor** [naturalcrit/homebrewery#1861]
Error: Bad Request

```
Error: Bad Request
    at Request.<anonymous> (https://homebrewery.naturalcrit.com/homebrew/bundle.js:72168:19)
    at Request.Emitter.emit (https://homebrewery.naturalcrit.com/homebrew/bundle.js:1768:20)
    at XMLHttpRequest.xhr.onreadystatechange (https://homebrewery.naturalcrit.com/homebrew/bundle.js:72477:10)
{
  "status": 400,
  "method": "POST",
  "url": "/api/newGoogle/"
}
```

**Comment by Gazook89** [comment]
This is a fairly common issue where your Google credentials have expired on the site. You'll need to log out and back in. Follow the steps in the discussion #1580 and you should be all set.
