### ISSUE TITLE
Google Drive issue

### ISSUE THREAD

**Issue by Ouren** [naturalcrit/homebrewery#1871]
Error: Bad Request

```
Error: Bad Request
    at Request.<anonymous> (https://homebrewery.naturalcrit.com/homebrew/bundle.js:72168:19)
    at Request.Emitter.emit (https://homebrewery.naturalcrit.com/homebrew/bundle.js:1768:20)
    at XMLHttpRequest.xhr.onreadystatechange (https://homebrewery.naturalcrit.com/homebrew/bundle.js:72477:10)
{
  "status": 400,
  "method": "POST",
  "url": "/api/newGoogle/"
}
```

**Comment by Ouren** [comment]
also, none of my brews that are saved in my gdrive are showing up in the list

**Comment by Gazook89** [comment]
Check out the steps outlined in discussion #1580 for how to resolve this.

**Comment by Gazook89** [comment]
Going to close this for now, but if the steps in #1580 didn't help we can reopen this issue.
