### ISSUE TITLE
Just didn't let me save

### ISSUE THREAD

**Issue by NovaStar556** [naturalcrit/homebrewery#1877]
Error: Bad Request

```
Error: Bad Request
    at Request.<anonymous> (https://homebrewery.naturalcrit.com/homebrew/bundle.js:72168:19)
    at Request.Emitter.emit (https://homebrewery.naturalcrit.com/homebrew/bundle.js:1768:20)
    at XMLHttpRequest.xhr.onreadystatechange (https://homebrewery.naturalcrit.com/homebrew/bundle.js:72477:10)
{
  "status": 400,
  "method": "POST",
  "url": "/api/newGoogle/"
}
```

**Comment by calculuschild** [comment]
Generally saving issues are due to expired Google drive credentials registered with the Homebrewery site. Follow the steps in Discussion #1580 for how to refresh your credentials to be able to save again. If those steps don't work, swing back here and we can dig deeper.

**Comment by Gazook89** [comment]
Going to close this for now, but can be reopened if those steps didn't help.
