### ISSUE TITLE
Trying to save a file on The Homebrewery

### ISSUE THREAD

**Issue by GMSkye** [naturalcrit/homebrewery#1878]
Error: Bad Request

```
Error: Bad Request
    at Request.<anonymous> (https://homebrewery.naturalcrit.com/homebrew/bundle.js:72168:19)
    at Request.Emitter.emit (https://homebrewery.naturalcrit.com/homebrew/bundle.js:1768:20)
    at XMLHttpRequest.xhr.onreadystatechange (https://homebrewery.naturalcrit.com/homebrew/bundle.js:72477:10)
{
  "status": 400,
  "method": "POST",
  "url": "/api/newGoogle/"
}
```

**Comment by Gazook89** [comment]
Generally this is an issue with expired google credentials.  Check out discussion #1580 for steps to resolve and you should be all set.  If not, swing back here and we can do a deeper dive.  Going to close this for now, but it can be reopened.
