### ISSUE TITLE
app seems down

### ISSUE THREAD

**Issue by alphywalfie** [naturalcrit/homebrewery#1884]
Error: Service Unavailable

```
Error: Service Unavailable
    at Request.<anonymous> (https://homebrewery.naturalcrit.com/homebrew/bundle.js:72178:19)
    at Request.Emitter.emit (https://homebrewery.naturalcrit.com/homebrew/bundle.js:1768:20)
    at XMLHttpRequest.xhr.onreadystatechange (https://homebrewery.naturalcrit.com/homebrew/bundle.js:72487:10)
{
  "status": 503,
  "method": "PUT",
  "url": "/api/update/wsV9W15UZGQQ"
}
```

**Comment by Gazook89** [comment]
Should be resolved now.  Going to close this issue for now, but let us know if it happens again.
