### ISSUE TITLE
Unable to save in Homebrewery

### ISSUE THREAD

**Issue by ChaelaMarieC** [naturalcrit/homebrewery#1968]
Error: Service Unavailable

```
Error: Service Unavailable
    at Request.<anonymous> (https://homebrewery.naturalcrit.com/homebrew/bundle.js:73820:19)
    at Request.Emitter.emit (https://homebrewery.naturalcrit.com/homebrew/bundle.js:1898:20)
    at XMLHttpRequest.xhr.onreadystatechange (https://homebrewery.naturalcrit.com/homebrew/bundle.js:74129:10)
{
  "status": 503,
  "method": "PUT",
  "url": "/api/update/HObQ02f8h9R2"
}
```

**Comment by Gazook89** [comment]
Check out the discussion and steps for resolution in #1580 

Going to close this issue for now as those steps should fix it for you, but if not, swing back here and we can take a deeper look.
