### ISSUE TITLE
Not saving

### ISSUE THREAD

**Issue by Sanityartist** [naturalcrit/homebrewery#1996]
Error: Service Unavailable

```
Error: Service Unavailable
    at Request.<anonymous> (https://homebrewery.naturalcrit.com/homebrew/bundle.js:73820:19)
    at Request.Emitter.emit (https://homebrewery.naturalcrit.com/homebrew/bundle.js:1898:20)
    at XMLHttpRequest.xhr.onreadystatechange (https://homebrewery.naturalcrit.com/homebrew/bundle.js:74129:10)
{
  "status": 503,
  "method": "PUT",
  "url": "/api/update/VjFO-pwd7oLW"
}
```

**Comment by calculuschild** [comment]
Looks like this was a temporary busy moment on the server. Let us know if it happens again.
