### ISSUE TITLE
saving issue

### ISSUE THREAD

**Issue by elliotiscoolsometimes** [naturalcrit/homebrewery#2048]
Error: Internal Server Error

```
Error: Internal Server Error
    at Request.<anonymous> (https://homebrewery.naturalcrit.com/homebrew/bundle.js:73924:19)
    at Request.Emitter.emit (https://homebrewery.naturalcrit.com/homebrew/bundle.js:1898:20)
    at XMLHttpRequest.xhr.onreadystatechange (https://homebrewery.naturalcrit.com/homebrew/bundle.js:74233:10)
{
  "status": 500,
  "method": "PUT",
  "url": "/api/update/Fh1FMCGBVGs2"
}
```

**Comment by Gazook89** [comment]
Checkout the discussion #1580 on this GitHub to see if that solves your issue. It likely stems from a Google drive issue which that should resolve.

**Comment by calculuschild** [comment]
Looks like this was a temporary busy moment on the server. Let us know if it happens again.
