### ISSUE TITLE
can't save on homebrewery 

### ISSUE THREAD

**Issue by UnboundMastaH** [naturalcrit/homebrewery#2057]
Error: Service Unavailable

```
Error: Service Unavailable
    at Request.<anonymous> (https://homebrewery.naturalcrit.com/homebrew/bundle.js:73924:19)
    at Request.Emitter.emit (https://homebrewery.naturalcrit.com/homebrew/bundle.js:1898:20)
    at XMLHttpRequest.xhr.onreadystatechange (https://homebrewery.naturalcrit.com/homebrew/bundle.js:74233:10)
{
  "status": 503,
  "method": "PUT",
  "url": "/api/update/dp4Kd-DvoiaU"
}
```

**Comment by calculuschild** [comment]
Looks like just a brief busy moment on our server. If you see this again, with the 503 error, just wait a few seconds and then try saving again.

Duplicate of #2058
