### ISSUE TITLE
Saving Issue (repeated, resolved by saving again)

### ISSUE THREAD

**Issue by Benhammer1313** [naturalcrit/homebrewery#2058]
Error: Service Unavailable

```
Error: Service Unavailable
    at Request.<anonymous> (https://homebrewery.naturalcrit.com/homebrew/bundle.js:73924:19)
    at Request.Emitter.emit (https://homebrewery.naturalcrit.com/homebrew/bundle.js:1898:20)
    at XMLHttpRequest.xhr.onreadystatechange (https://homebrewery.naturalcrit.com/homebrew/bundle.js:74233:10)
{
  "status": 503,
  "method": "PUT",
  "url": "/api/update/OjcvOChkYKcX"
}
```

**Comment by calculuschild** [comment]
Thanks for the report. That 503 status looks like our server just had a hiccup at that particular moment.

We can probably add a more specific error message when this happens: "Our server is a bit busy. Wait a few seconds and then try saving again."
