### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by Kasputin** [naturalcrit/homebrewery#2081]
Error: Service Unavailable

```
Error: Service Unavailable
    at Request.<anonymous> (https://homebrewery.naturalcrit.com/homebrew/bundle.js:73924:19)
    at Request.Emitter.emit (https://homebrewery.naturalcrit.com/homebrew/bundle.js:1898:20)
    at XMLHttpRequest.xhr.onreadystatechange (https://homebrewery.naturalcrit.com/homebrew/bundle.js:74233:10)
{
  "status": 503,
  "method": "PUT",
  "url": "/api/update/bFnHaIvbYFOI"
}
```

**Comment by calculuschild** [comment]
Looks like our servers stalled for a couple minutes. Should be working again now.
