### ISSUE TITLE
Restoring trashed Google Drive file has potential for duplicate ID conflict

### ISSUE THREAD

**Issue by calculuschild** [naturalcrit/homebrewery#2099]
Due to the change in #2089 to persist `shareID` and `editID` between Google Drive transfers. Since we don't fully delete the transferred file from the user's Google drive, but just send it to the Trash (in case it was accidental), recovering that file and then attempting to also send it to the Homebrewery will naturally result in a conflict in a duplicate ID.

However, this error manifests as the "Your google credentials are expired" popup. Simply providing a correct error message might be all we need to do here. The chance of this happening is pretty small I think.

#### Relevant server error:
```
MongoServerError: E11000 duplicate key error collection: homebrewery.homebrews index: shareId_1 dup key: { shareId: "eqnUtZ6a95aa" }
    at C:\Users\Trevor\Documents\GitHub\homebrewery\node_modules\mongodb\lib\operations\insert.js:51:33
    at C:\Users\Trevor\Documents\GitHub\homebrewery\node_modules\mongodb\lib\cmap\connection_pool.js:273:25
    at handleOperationResult (C:\Users\Trevor\Documents\GitHub\homebrewery\node_modules\mongodb\lib\sdam\server.js:363:9)
    at MessageStream.messageHandler (C:\Users\Trevor\Documents\GitHub\homebrewery\node_modules\mongodb\lib\cmap\connection.js:474:9)
    at MessageStream.emit (node:events:390:28)
    at processIncomingData (C:\Users\Trevor\Documents\GitHub\homebrewery\node_modules\mongodb\lib\cmap\message_stream.js:108:16)
    at MessageStream._write (C:\Users\Trevor\Documents\GitHub\homebrewery\node_modules\mongodb\lib\cmap\message_stream.js:28:9)
    at writeOrBuffer (node:internal/streams/writable:389:12)
    at _write (node:internal/streams/writable:330:10)
    at MessageStream.Writable.write (node:internal/streams/writable:334:10) {
  index: 0,
  code: 11000,
  keyPattern: { shareId: 1 },
  keyValue: { shareId: 'eqnUtZ6a95aa' }MongoServerError: E11000 duplicate key error collection: homebrewery.homebrews index: shareId_1 dup key: { shareId: "eqnUtZ6a95aa" }
    at C:\Users\Trevor\Documents\GitHub\homebrewery\node_modules\mongodb\lib\operations\insert.js:51:33
    at C:\Users\Trevor\Documents\GitHub\homebrewery\node_modules\mongodb\lib\cmap\connection_pool.js:273:25
    at handleOperationResult (C:\Users\Trevor\Documents\GitHub\homebrewery\node_modules\mongodb\lib\sdam\server.js:363:9)
    at MessageStream.messageHandler (C:\Users\Trevor\Documents\GitHub\homebrewery\node_modules\mongodb\lib\cmap\connection.js:474:9)
    at MessageStream.emit (node:events:390:28)
    at processIncomingData (C:\Users\Trevor\Documents\GitHub\homebrewery\node_modules\mongodb\lib\cmap\message_stream.js:108:16)
    at MessageStream._write (C:\Users\Trevor\Documents\GitHub\homebrewery\node_modules\mongodb\lib\cmap\message_stream.js:28:9)
    at writeOrBuffer (node:internal/streams/writable:389:12)
    at _write (node:internal/streams/writable:330:10)
    at MessageStream.Writable.write (node:internal/streams/writable:334:10) {
  index: 0,
  code: 11000,
  keyPattern: { shareId: 1 },
  keyValue: { shareId: 'eqnUtZ6a95aa' }
```

**Comment by 5e-Cleric** [comment]
Trashed brews are viewable in the tool, with a popup showing that they are in the trash, is this still an issue?

**Comment by calculuschild** [comment]
That is a separate issue.

The issue is this (not sure if still exists, but should test):
1) Create a brew linked to a Google Drive
2) Transfer the brew to HB. The original Google Drive file is moved to Google Drive trash
3) Open Google Drive trash. Find the deleted file and restore it
4) You now have two files with the same shareId, one on HB and one from Google Drive
5) Attempt to send the Google Drive file to HB
6) Error. Duplicate file ID.

**Comment by dbolack-ab** [comment]
I'm looking at the code here and I *don't* see how this can happen.

@app.js Lines 319 through 334

```
		// If stub matches file from Google, use Google metadata over stub metadata
		if(googleBrews && googleBrews.length > 0) {
			for (const brew of brews.filter((brew)=>brew.googleId)) {
				const match = googleBrews.findIndex((b)=>b.editId === brew.editId);
				if(match !== -1) {
					brew.googleId = googleBrews[match].googleId;
					brew.pageCount = googleBrews[match].pageCount;
					brew.renderer = googleBrews[match].renderer;
					brew.version = googleBrews[match].version;
					brew.webViewLink = googleBrews[match].webViewLink;
					googleBrews.splice(match, 1);
				}
			}

			//Remaining unstubbed google brews display current user as author
			googleBrews = googleBrews.map((brew)=>({ ...brew, authors: [req.account.username] }));
			brews = _.concat(brews, googleBrews);
```

where googleBrews is an array of stub-like objects representing files from the GDrive folder.

**Comment by calculuschild** [comment]
They might not show both in the user page then, but I think the one that *is* shown might still point to the Google Drive copy if you open it from the user page.

Regardless of what the user page is doing though, I think it's still possible to visit the Google Drive copy of the file via an old link in the browser or the "recent brews", and then trigger the duplicate transfer to HB.

I think the solution is still to just add a proper error message.

**Comment by Gazook89** [comment]
Can we just delete the Google version when we transfer it to HB? Not just mark it at “trashed” but actually properly delete it? I seem to remember reading that there are two distinct functions for this. 

Alternatively, rewrite the brewID to something like 00000 before trashing it.

**Comment by calculuschild** [comment]
> Can we just delete the Google version when we transfer it to HB? Not just mark it at “trashed” but actually properly delete it? I seem to remember reading that there are two distinct functions for this.

I'm not opposed to this. Yes there are two separate functions for trash vs fully delete.

> Alternatively, rewrite the brewID to something like 00000 before trashing it.

The problem here is if we do just put it in the trash, and a user wants to recover it, all links to that document are broken. Ideally "just trashing" should be a fully recoverable situation.

**Comment by dbolack-ab** [comment]
@calculuschild Is this problem mitigated by retiring the Drive scan?
