### ISSUE TITLE
Save Issue

### ISSUE THREAD

**Issue by PelliUser** [naturalcrit/homebrewery#2103]
Error: Forbidden

```
Error: Forbidden
    at Request.<anonymous> (https://homebrewery.naturalcrit.com/homebrew/bundle.js:73934:19)
    at Request.Emitter.emit (https://homebrewery.naturalcrit.com/homebrew/bundle.js:1898:20)
    at XMLHttpRequest.xhr.onreadystatechange (https://homebrewery.naturalcrit.com/homebrew/bundle.js:74243:10)
{
  "status": 403,
  "method": "POST",
  "url": "/api?transferToGoogle=true"
}
```

**Comment by Gazook89** [comment]
Likely your google credentials have expired on the site. Try logging out of Homebrewery and back in with your google credentials.

As of March 28th, there is a new Logout button that can be found by hovering over your username in the top right of the screen.  Or follow the steps in #1580.
