### ISSUE TITLE
Save error encountered

### ISSUE THREAD

**Issue by Objulen** [naturalcrit/homebrewery#2141]
Error: Service Unavailable

```
Error: Service Unavailable
    at Request.<anonymous> (https://homebrewery.naturalcrit.com/homebrew/bundle.js:73949:19)
    at Request.Emitter.emit (https://homebrewery.naturalcrit.com/homebrew/bundle.js:1898:20)
    at XMLHttpRequest.xhr.onreadystatechange (https://homebrewery.naturalcrit.com/homebrew/bundle.js:74258:10)
{
  "status": 503,
  "method": "PUT",
  "url": "/api/update/lyB0t3Yfkpd7"
}
```

**Comment by calculuschild** [comment]
Looks like this was a temporary busy moment on the server. Let us know if it happens again.
