### ISSUE TITLE
Save report

### ISSUE THREAD

**Issue by Baravis** [naturalcrit/homebrewery#2143]
Error: Service Unavailable

```
Error: Service Unavailable
    at Request.<anonymous> (https://homebrewery.naturalcrit.com/homebrew/bundle.js:73949:19)
    at Request.Emitter.emit (https://homebrewery.naturalcrit.com/homebrew/bundle.js:1898:20)
    at XMLHttpRequest.xhr.onreadystatechange (https://homebrewery.naturalcrit.com/homebrew/bundle.js:74258:10)
{
  "status": 503,
  "method": "PUT",
  "url": "/api/update/cP4xTVICgEFJ"
}
```

**Comment by jeddai** [comment]
Still trying to figure out what's happened, but HB is down right now for everyone. It may not be back up until morning (EST). 

For your brew, please don't close the window and save its currents state in an external text editor for now. Will update this issue as we find out more.
