### ISSUE TITLE
Saving issue

### ISSUE THREAD

**Issue by kivielalmekyde** [naturalcrit/homebrewery#2201]
Error: Service Unavailable

```
Error: Service Unavailable
    at Request.<anonymous> (https://homebrewery.naturalcrit.com/homebrew/bundle.js:75255:19)
    at Emitter.emit (https://homebrewery.naturalcrit.com/homebrew/bundle.js:1966:20)
    at xhr.onreadystatechange (https://homebrewery.naturalcrit.com/homebrew/bundle.js:75564:10)
{
  "status": 503,
  "method": "PUT",
  "url": "/api/update/0BJGHh6aGmpi"
}
```

**Comment by calculuschild** [comment]
From our logs, it looks like the server was just a little busy at that moment. It looks like the problem resolved itself about 20 seconds later. I'm assuming you were able to get it to save shortly after. Let us know if the issue persists.
