### ISSUE TITLE
Error keeps persisting

### ISSUE THREAD

**Issue by juanpang101** [naturalcrit/homebrewery#2204]
Error: Forbidden

```
Error: Forbidden
    at Request.<anonymous> (https://homebrewery.naturalcrit.com/homebrew/bundle.js:75255:19)
    at Emitter.emit (https://homebrewery.naturalcrit.com/homebrew/bundle.js:1966:20)
    at xhr.onreadystatechange (https://homebrewery.naturalcrit.com/homebrew/bundle.js:75564:10)
{
  "status": 403,
  "method": "PUT",
  "url": "/api/update/tQatNVF1IDzA"
}
```

**Comment by calculuschild** [comment]
From our logs, it looks like you might be trying to transfer a brew to your Google Drive, but Google is sending back an error that "The user's Drive storage quota has been exceeded." Your Google Drive might be full.
