### ISSUE TITLE
Issue uploading Thumbnail URL

### ISSUE THREAD

**Issue by ShamelessHero502** [naturalcrit/homebrewery#2245]
Error: Forbidden

```
Error: Forbidden
    at Request.<anonymous> (https://homebrewery.naturalcrit.com/homebrew/bundle.js:75320:19)
    at Emitter.emit (https://homebrewery.naturalcrit.com/homebrew/bundle.js:1966:20)
    at xhr.onreadystatechange (https://homebrewery.naturalcrit.com/homebrew/bundle.js:75629:10)
{
  "status": 403,
  "method": "PUT",
  "url": "/api/update/2RabwdG5S2fB"
}
```

**Comment by calculuschild** [comment]
Looks like this was a temporary busy moment on the server. Let us know if it happens again.
