### ISSUE TITLE
bho non va

### ISSUE THREAD

**Issue by Papejima** [naturalcrit/homebrewery#2277]
Error: Client Disconnected

```
Error: Client Disconnected
    at Request.<anonymous> (https://homebrewery.naturalcrit.com/homebrew/bundle.js:75320:19)
    at Emitter.emit (https://homebrewery.naturalcrit.com/homebrew/bundle.js:1966:20)
    at xhr.onreadystatechange (https://homebrewery.naturalcrit.com/homebrew/bundle.js:75629:10)
{
  "status": 499,
  "method": "PUT",
  "url": "/api/update/8B6Nm91bHRsw"
}
```

**Comment by calculuschild** [comment]
Looks like this was a temporary busy moment on the server. Let us know if it happens again.
