### ISSUE TITLE
Problem Saving

### ISSUE THREAD

**Issue by phicups** [naturalcrit/homebrewery#2281]
Error: Service Unavailable

```
Error: Service Unavailable
    at Request.<anonymous> (https://homebrewery.naturalcrit.com/homebrew/bundle.js:75320:19)
    at Emitter.emit (https://homebrewery.naturalcrit.com/homebrew/bundle.js:1966:20)
    at xhr.onreadystatechange (https://homebrewery.naturalcrit.com/homebrew/bundle.js:75629:10)
{
  "status": 503,
  "method": "PUT",
  "url": "/api/update/mKkIvAZ3ptjo"
}
```

**Comment by calculuschild** [comment]
Should be working now. Looks like just a tiny hiccup on the server.
