### ISSUE TITLE
not really sure what happened, was just using the tool and saw the error message.

### ISSUE THREAD

**Issue by Johnny2136** [naturalcrit/homebrewery#2282]
Error: Service Unavailable

```
Error: Service Unavailable
    at Request.<anonymous> (https://homebrewery.naturalcrit.com/homebrew/bundle.js:75320:19)
    at Emitter.emit (https://homebrewery.naturalcrit.com/homebrew/bundle.js:1966:20)
    at xhr.onreadystatechange (https://homebrewery.naturalcrit.com/homebrew/bundle.js:75629:10)
{
  "status": 503,
  "method": "PUT",
  "url": "/api/update/GKFvrbSs5Cx_"
}
```

**Comment by calculuschild** [comment]
Looks like just a temporary hiccup on our servers. Should be working now.

**Comment by Johnny2136** [comment]
Yeah, I never saw anything like that before.
