### ISSUE TITLE
Saving

### ISSUE THREAD

**Issue by tdpst18** [naturalcrit/homebrewery#2293]
Error: Service Unavailable

```
Error: Service Unavailable
    at Request.<anonymous> (https://homebrewery.naturalcrit.com/homebrew/bundle.js:75320:19)
    at Emitter.emit (https://homebrewery.naturalcrit.com/homebrew/bundle.js:1966:20)
    at xhr.onreadystatechange (https://homebrewery.naturalcrit.com/homebrew/bundle.js:75629:10)
{
  "status": 503,
  "method": "PUT",
  "url": "/api/update/RogAeQgTSoj1"
}
```

**Comment by calculuschild** [comment]
Looks like this was a temporary busy moment on the server. Let us know if it happens again.
