### ISSUE TITLE
Problem Saving

### ISSUE THREAD

**Issue by PhylsorKyrem** [naturalcrit/homebrewery#2321]
Error: Internal Server Error

```
Error: Internal Server Error
    at Request.<anonymous> (https://homebrewery.naturalcrit.com/homebrew/bundle.js:75346:19)
    at Emitter.emit (https://homebrewery.naturalcrit.com/homebrew/bundle.js:1966:20)
    at xhr.onreadystatechange (https://homebrewery.naturalcrit.com/homebrew/bundle.js:75655:10)
{
  "status": 500,
  "method": "PUT",
  "url": "/api/update/P24ZczDrJxt1"
}
```

**Comment by calculuschild** [comment]
Thanks for the report! See #2322 for more details!
