### ISSUE TITLE
There is a problem in saving

### ISSUE THREAD

**Issue by akiva-evenchen** [naturalcrit/homebrewery#2339]
Error: Forbidden

```
Error: Forbidden
    at Request.<anonymous> (https://homebrewery.naturalcrit.com/homebrew/bundle.js:75346:19)
    at Emitter.emit (https://homebrewery.naturalcrit.com/homebrew/bundle.js:1966:20)
    at xhr.onreadystatechange (https://homebrewery.naturalcrit.com/homebrew/bundle.js:75655:10)
{
  "status": 403,
  "method": "PUT",
  "url": "/api/update/DeG4Xc7WbIGi"
}
```

**Comment by calculuschild** [comment]
Another case of #2322.

@akiva-evenchen Fortunately this should only be a temporary issue. Wait a moment and then try again
