### ISSUE TITLE
20220909 Saving Error

### ISSUE THREAD

**Issue by gui8311** [naturalcrit/homebrewery#2350]
Error: Internal Server Error

```
Error: Internal Server Error
    at Request.<anonymous> (https://homebrewery.naturalcrit.com/homebrew/bundle.js:75346:19)
    at Emitter.emit (https://homebrewery.naturalcrit.com/homebrew/bundle.js:1966:20)
    at xhr.onreadystatechange (https://homebrewery.naturalcrit.com/homebrew/bundle.js:75655:10)
{
  "status": 500,
  "method": "PUT",
  "url": "/api/update/h8bIbtxS8zGR"
}
```

**Comment by gui8311** [comment]
Dear Homebrewery team,

Error Description:
This error has been appearing to me multiple times today - first day using the website more extensively.
I am able to save without problems for a while (1 hour roughly) until this error happens.
The error is more of a nuisance right now than anything else, since refreshing the page seems to fix the problem for a while. It does result in me loosing my most recent edits though (unless I copy the code manually to a file on my pc).

Possible Link:
Before this error first appeared I was asked to link a google account to my homebrewery account, since no linked google account had been found. I had not received this message ever before (my account is not new, but I barely used the website until today). I did what was asked and linked the account to a google account of mine. Now this error appears every now and then.

Hope this report helps fix the issue. If you need more info, feel free to contact me.

All the best,
gui8312

**Comment by calculuschild** [comment]
Looking at our logs it's seems we're just getting bits of high traffic when you tried to save. See #2322

We are working on a fix to remove the bottleneck here.

**Comment by gui8311** [comment]
alright, thank you :)
