### ISSUE TITLE
Prompted to Report this error

### ISSUE THREAD

**Issue by cduff4464** [naturalcrit/homebrewery#2353]
Error: Forbidden

```
Error: Forbidden
    at Request.<anonymous> (https://homebrewery.naturalcrit.com/homebrew/bundle.js:75346:19)
    at Emitter.emit (https://homebrewery.naturalcrit.com/homebrew/bundle.js:1966:20)
    at xhr.onreadystatechange (https://homebrewery.naturalcrit.com/homebrew/bundle.js:75655:10)
{
  "status": 403,
  "method": "PUT",
  "url": "/api/update/576WGNdboxZ1"
}
```

**Comment by cduff4464** [comment]
Yes, I saved it all to a txt file and it ended up working later that day. I’m not sure what happened.

**Comment by Gazook89** [comment]
Hm, okay.  Going to close this one out!
