### ISSUE TITLE
Was Copying an Image's Link

### ISSUE THREAD

**Issue by PhylsorKyrem** [naturalcrit/homebrewery#2361]
Error: Forbidden

```
Error: Forbidden
    at Request.<anonymous> (https://homebrewery.naturalcrit.com/homebrew/bundle.js:75346:19)
    at Emitter.emit (https://homebrewery.naturalcrit.com/homebrew/bundle.js:1966:20)
    at xhr.onreadystatechange (https://homebrewery.naturalcrit.com/homebrew/bundle.js:75655:10)
{
  "status": 403,
  "method": "PUT",
  "url": "/api/update/lxWixraxMPY5"
}
```

**Comment by calculuschild** [comment]
Links that are too long (>124 characters) don't work at the moment. Try a shorter link if you can for now (copy the file to imgur perhaps?).

Duplicate of #2351
