### ISSUE TITLE
error

### ISSUE THREAD

**Issue by BigBird99** [naturalcrit/homebrewery#2365]
Error: Internal Server Error

```
Error: Internal Server Error
    at Request.<anonymous> (https://homebrewery.naturalcrit.com/homebrew/bundle.js:75346:19)
    at Emitter.emit (https://homebrewery.naturalcrit.com/homebrew/bundle.js:1966:20)
    at xhr.onreadystatechange (https://homebrewery.naturalcrit.com/homebrew/bundle.js:75655:10)
{
  "status": 500,
  "method": "PUT",
  "url": "/api/update/lGYvVCuyJ9bV"
}
```

**Comment by calculuschild** [comment]
For now, the solution is simply to wait a short moment and then try again. Looks like we had a burst of traffic going to Google Drive and it was too much at once.

See #2322 for more details.
