### ISSUE TITLE
issue saving

### ISSUE THREAD

**Issue by Mark-Aquamarine** [naturalcrit/homebrewery#2385]
Error: Service Unavailable

```
Error: Service Unavailable
    at Request.<anonymous> (https://homebrewery.naturalcrit.com/homebrew/bundle.js:75346:19)
    at Emitter.emit (https://homebrewery.naturalcrit.com/homebrew/bundle.js:1966:20)
    at xhr.onreadystatechange (https://homebrewery.naturalcrit.com/homebrew/bundle.js:75655:10)
{
  "status": 503,
  "method": "PUT",
  "url": "/api/update/SltTtJmEGeGE"
}
```

**Comment by calculuschild** [comment]
Looks like our server just had a temporary hiccup. Should be working again after a minute or two.
