### ISSUE TITLE
Unable to Save

### ISSUE THREAD

**Issue by wcaldwell32** [naturalcrit/homebrewery#2402]
Error: Service Unavailable

```
Error: Service Unavailable
    at Request.<anonymous> (https://homebrewery.naturalcrit.com/homebrew/bundle.js:75346:19)
    at Emitter.emit (https://homebrewery.naturalcrit.com/homebrew/bundle.js:1966:20)
    at xhr.onreadystatechange (https://homebrewery.naturalcrit.com/homebrew/bundle.js:75655:10)
{
  "status": 503,
  "method": "PUT",
  "url": "/api/update/_yORVhsmOvtr"
}
```

**Comment by 5e-Cleric** [comment]
Error 503 due to overloaded server, closing.
