### ISSUE TITLE
Issues with DNS recently, could be connected

### ISSUE THREAD

**Issue by Chamo5096** [naturalcrit/homebrewery#2423]
Error: Forbidden

```
Error: Forbidden
    at Request.<anonymous> (https://homebrewery.naturalcrit.com/homebrew/bundle.js:75346:19)
    at Emitter.emit (https://homebrewery.naturalcrit.com/homebrew/bundle.js:1966:20)
    at xhr.onreadystatechange (https://homebrewery.naturalcrit.com/homebrew/bundle.js:75655:10)
{
  "status": 403,
  "method": "PUT",
  "url": "/api/update/Rs01etd8dGOw"
}
```

**Comment by dbolack-ab** [comment]
Has this continued?

**Comment by 5e-Cleric** [comment]
this is probably an issue of an unlogged user or user logged in the wrong account, doesn't look like they had further problems, closing.
