### ISSUE TITLE
"Auto Save" not working

### ISSUE THREAD

**Issue by RusselH3X** [naturalcrit/homebrewery#2486]
### Error Code

```shell
Error: Client Disconnected


Error: Client Disconnected
    at Request.<anonymous> (https://homebrewery.naturalcrit.com/homebrew/bundle.js:75356:19)
    at Emitter.emit (https://homebrewery.naturalcrit.com/homebrew/bundle.js:1966:20)
    at xhr.onreadystatechange (https://homebrewery.naturalcrit.com/homebrew/bundle.js:75665:10)
{
  "status": 499,
  "method": "PUT",
  "url": "/api/update/iTdCE0b2r8RR"
}
```

### Your description of what happened:

"Auto Save" not working

**Comment by calculuschild** [comment]
This error indicates your browser lost connection in the middle of saving. Did you have spotty internet by chance? Is this still an issue for you?

**Comment by 5e-Cleric** [comment]
3 months without a reply, user probably disconnected, closing.
