### ISSUE TITLE
for some reason my monster statblocks are having trouble saving

### ISSUE THREAD

**Issue by UmberCel** [naturalcrit/homebrewery#2541]
### Error Code

```shell
Error: Forbidden


Error: Forbidden
    at Request.<anonymous> (https://homebrewery.naturalcrit.com/homebrew/bundle.js:75006:19)
    at Emitter.emit (https://homebrewery.naturalcrit.com/homebrew/bundle.js:1966:20)
    at xhr.onreadystatechange (https://homebrewery.naturalcrit.com/homebrew/bundle.js:75315:10)
{
  "status": 403,
  "method": "PUT",
  "url": "/api/update/gO1mAaP3Y090"
}
```
```


### Your description of what happened:

all the website said was that it is having a problem saving and to report it here

**Comment by calculuschild** [comment]
Is this still happening? We may have had a temporary hiccup on our servers being too busy.

**Comment by UmberCel** [comment]
no, its no longer happening. it seems to have fixed itself. But thank you for making such an incredible website.
