### ISSUE TITLE
Onis the Homebrewery

### ISSUE THREAD

**Issue by klosseia** [naturalcrit/homebrewery#2574]
### Error Code

```shell
Error: Conflict


Error: Conflict
    at Request.<anonymous> (https://homebrewery.naturalcrit.com/homebrew/bundle.js:76355:19)
    at Emitter.emit (https://homebrewery.naturalcrit.com/homebrew/bundle.js:1966:20)
    at xhr.onreadystatechange (https://homebrewery.naturalcrit.com/homebrew/bundle.js:76664:10)
{
  "status": 409,
  "method": "PUT",
  "url": "/api/update/AGhMrl-NJuCK"
}
```
```


### Your description of what happened:

Cant save

**Comment by calculuschild** [comment]
Please copy your brew text somewhere safe and refresh the page. We may have a server hiccup happening.
