### ISSUE TITLE
wont save

### ISSUE THREAD

**Issue by solangel777** [naturalcrit/homebrewery#2631]
### Error Code

```shell
Error: Precondition Failed


Error: Precondition Failed
    at Request.<anonymous> (https://homebrewery.naturalcrit.com/homebrew/bundle.js:76373:19)
    at Emitter.emit (https://homebrewery.naturalcrit.com/homebrew/bundle.js:1966:20)
    at xhr.onreadystatechange (https://homebrewery.naturalcrit.com/homebrew/bundle.js:76682:10)
{
  "status": 412,
  "method": "PUT",
  "url": "/api/update/mbZVX6v7AW8J"
}
```
```


### Your description of what happened:

Working on my ttrpg and i cant save it at all. my other homebreweries save just fine

**Comment by solangel777** [comment]
thank you i nearly had a heart attack.

**Comment by calculuschild** [comment]
No worries. In fact this update contains a better error message so next time around you will get clear instructions when you need to update instead of the scary message you got.
