### ISSUE TITLE
autosave broke again

### ISSUE THREAD

**Issue by swordsart** [naturalcrit/homebrewery#2645]
### Error Code

```shell
Error: Service Unavailable


Error: Service Unavailable
    at Request.<anonymous> (https://homebrewery.naturalcrit.com/homebrew/bundle.js:76373:19)
    at Emitter.emit (https://homebrewery.naturalcrit.com/homebrew/bundle.js:1966:20)
    at xhr.onreadystatechange (https://homebrewery.naturalcrit.com/homebrew/bundle.js:76682:10)
{
  "status": 503,
  "method": "PUT",
  "url": "/api/update/9TzgVd_MbIS6"
}
```
```


### Your description of what happened:

autosave broke again

**Comment by 5e-Cleric** [comment]
This was probably because the server was receiving a lot of requests at that time and was abnormally busy, it should work now, could you try again, please?
