### ISSUE TITLE
Brew crashes due to multiple text formatting tags

### ISSUE THREAD

**Issue by Kiriela** [naturalcrit/homebrewery#2712]
### Renderer

v3

### Browser

Chrome

### Operating System

Windows

### What happened?

I was fixing my table of contents for my brew (which is still bricked), and suddenly the entire browser went into a full white screen aside from the address bar at the top. After some digging, I was able to determine that this is the result of putting two {} text formatting brackets below one another (presumably the second one attempts to format the first one, which leads to undesired behaviour). The code provided is an example of what I had.

While I was able to save and create another brew using the source code from this one, I would prefer to still keep the previous one to use the same link, as well as partially to keep it as one of my top viewed brews to ease finding it in my pile of brews on my profile.

If you are able to manually change the contents of a brew, please remove the provided bit from page 2 of brew:
https://homebrewery.naturalcrit.com/edit/PRK9DJ9Cm

### Code

```gfm
##### [Grievous Wounds](#p27)
{color:#73310e,font-size:125%}
{text-align:center}
```

**Comment by G-Ambatte** [comment]
This code results in the following errors in the browser console:

```
Uncaught RangeError: Maximum call stack size exceeded
Please report this to https://github.com/markedjs/marked.
    at Parser.parse (bundle.js:69588:63)
    at Object.renderer (bundle.js:94776:30)
    at Parser.parse (bundle.js:69588:63)
    at Object.renderer (bundle.js:94776:30)
    at Parser.parse (bundle.js:69588:63)
    at Object.renderer (bundle.js:94776:30)
    at Parser.parse (bundle.js:69588:63)
    at Object.renderer (bundle.js:94776:30)
    at Parser.parse (bundle.js:69588:63)
    at Object.renderer (bundle.js:94776:30)
parse @ bundle.js:69588
renderer @ bundle.js:94776
parse @ bundle.js:69588
renderer @ bundle.js:94776
parse @ bundle.js:69588
renderer @ bundle.js:94776
parse @ bundle.js:69588
renderer @ bundle.js:94776
parse @ bundle.js:69588
renderer @ bundle.js:94776
parse @ bundle.js:69588
renderer @ bundle.js:94776
parse @ bundle.js:69588
renderer @ bundle.js:94776
parse @ bundle.js:69588
renderer @ bundle.js:94776
parse @ bundle.js:69588
renderer @ bundle.js:94776
parse @ bundle.js:69588
renderer @ bundle.js:94776
parse @ bundle.js:69588
renderer @ bundle.js:94776
parse @ bundle.js:69588
renderer @ bundle.js:94776
parse @ bundle.js:69588
renderer @ bundle.js:94776
parse @ bundle.js:69588
renderer @ bundle.js:94776
parse @ bundle.js:69588
renderer @ bundle.js:94776
parse @ bundle.js:69588
renderer @ bundle.js:94776
parse @ bundle.js:69588
renderer @ bundle.js:94776
parse @ bundle.js:69588
renderer @ bundle.js:94776
parse @ bundle.js:69588
renderer @ bundle.js:94776
parse @ bundle.js:69588
renderer @ bundle.js:94776
parse @ bundle.js:69588
renderer @ bundle.js:94776
parse @ bundle.js:69588
renderer @ bundle.js:94776
parse @ bundle.js:69588
renderer @ bundle.js:94776
parse @ bundle.js:69588
renderer @ bundle.js:94776
parse @ bundle.js:69588
renderer @ bundle.js:94776
parse @ bundle.js:69588
renderer @ bundle.js:94776
parse @ bundle.js:69588
renderer @ bundle.js:94776
parse @ bundle.js:69588
renderer @ bundle.js:94776
parse @ bundle.js:69588
renderer @ bundle.js:94776
parse @ bundle.js:69588
renderer @ bundle.js:94776
parse @ bundle.js:69588
renderer @ bundle.js:94776
parse @ bundle.js:69588
renderer @ bundle.js:94776
parse @ bundle.js:69588
renderer @ bundle.js:94776
parse @ bundle.js:69588
renderer @ bundle.js:94776
parse @ bundle.js:69588
renderer @ bundle.js:94776
parse @ bundle.js:69588
renderer @ bundle.js:94776
parse @ bundle.js:69588
renderer @ bundle.js:94776
parse @ bundle.js:69588
renderer @ bundle.js:94776
parse @ bundle.js:69588
renderer @ bundle.js:94776
parse @ bundle.js:69588
renderer @ bundle.js:94776
parse @ bundle.js:69588
renderer @ bundle.js:94776
parse @ bundle.js:69588
renderer @ bundle.js:94776
parse @ bundle.js:69588
renderer @ bundle.js:94776
parse @ bundle.js:69588
renderer @ bundle.js:94776
parse @ bundle.js:69588
renderer @ bundle.js:94776
parse @ bundle.js:69588
renderer @ bundle.js:94776
parse @ bundle.js:69588
renderer @ bundle.js:94776
parse @ bundle.js:69588
renderer @ bundle.js:94776
parse @ bundle.js:69588
renderer @ bundle.js:94776
parse @ bundle.js:69588
renderer @ bundle.js:94776
parse @ bundle.js:69588
renderer @ bundle.js:94776
parse @ bundle.js:69588
renderer @ bundle.js:94776
parse @ bundle.js:69588
renderer @ bundle.js:94776
parse @ bundle.js:69588
renderer @ bundle.js:94776
parse @ bundle.js:69588
renderer @ bundle.js:94776
parse @ bundle.js:69588
renderer @ bundle.js:94776
parse @ bundle.js:69588
renderer @ bundle.js:94776
parse @ bundle.js:69588
renderer @ bundle.js:94776
parse @ bundle.js:69588
renderer @ bundle.js:94776
parse @ bundle.js:69588
renderer @ bundle.js:94776
parse @ bundle.js:69588
renderer @ bundle.js:94776
parse @ bundle.js:69588
renderer @ bundle.js:94776
parse @ bundle.js:69588
renderer @ bundle.js:94776
parse @ bundle.js:69588
renderer @ bundle.js:94776
parse @ bundle.js:69588
renderer @ bundle.js:94776
parse @ bundle.js:69588
renderer @ bundle.js:94776
parse @ bundle.js:69588
renderer @ bundle.js:94776
parse @ bundle.js:69588
renderer @ bundle.js:94776
parse @ bundle.js:69588
renderer @ bundle.js:94776
parse @ bundle.js:69588
renderer @ bundle.js:94776
parse @ bundle.js:69588
renderer @ bundle.js:94776
parse @ bundle.js:69588
renderer @ bundle.js:94776
parse @ bundle.js:69588
renderer @ bundle.js:94776
parse @ bundle.js:69588
renderer @ bundle.js:94776
parse @ bundle.js:69588
renderer @ bundle.js:94776
parse @ bundle.js:69588
renderer @ bundle.js:94776
parse @ bundle.js:69588
renderer @ bundle.js:94776
parse @ bundle.js:69588
renderer @ bundle.js:94776
parse @ bundle.js:69588
renderer @ bundle.js:94776
parse @ bundle.js:69588
renderer @ bundle.js:94776
parse @ bundle.js:69588
renderer @ bundle.js:94776
parse @ bundle.js:69588
renderer @ bundle.js:94776
parse @ bundle.js:69588
renderer @ bundle.js:94776
parse @ bundle.js:69588
renderer @ bundle.js:94776
parse @ bundle.js:69588
renderer @ bundle.js:94776
parse @ bundle.js:69588
renderer @ bundle.js:94776
parse @ bundle.js:69588
renderer @ bundle.js:94776
parse @ bundle.js:69588
renderer @ bundle.js:94776
parse @ bundle.js:69588
renderer @ bundle.js:94776
parse @ bundle.js:69588
renderer @ bundle.js:94776
parse @ bundle.js:69588
renderer @ bundle.js:94776
parse @ bundle.js:69588
renderer @ bundle.js:94776
parse @ bundle.js:69588
renderer @ bundle.js:94776
parse @ bundle.js:69588
renderer @ bundle.js:94776
parse @ bundle.js:69588
renderer @ bundle.js:94776
parse @ bundle.js:69588
renderer @ bundle.js:94776
parse @ bundle.js:69588
renderer @ bundle.js:94776
parse @ bundle.js:69588
renderer @ bundle.js:94776
parse @ bundle.js:69588
renderer @ bundle.js:94776
parse @ bundle.js:69588
renderer @ bundle.js:94776
react_devtools_backend.js:2655 The above error occurred in the <BrewRenderer> component:

    at <anonymous> (http://localhost:8000/homebrew/bundle.js:2897:37)
    at div
    at <anonymous> (http://localhost:8000/homebrew/bundle.js:2897:37)
    at div
    at <anonymous> (http://localhost:8000/homebrew/bundle.js:2897:37)
    at div
    at div
    at <anonymous> (http://localhost:8000/homebrew/bundle.js:2897:37)
    at WithRoute (http://localhost:8000/homebrew/bundle.js:78559:16)
    at RenderedRoute (http://localhost:8000/homebrew/bundle.js:92150:29)
    at Routes (http://localhost:8000/homebrew/bundle.js:92640:26)
    at div
    at Router (http://localhost:8000/homebrew/bundle.js:92570:32)
    at StaticRouter (http://localhost:8000/homebrew/bundle.js:91239:23)
    at <anonymous> (http://localhost:8000/homebrew/bundle.js:2897:37)

Consider adding an error boundary to your tree to customize error handling behavior.
Visit https://reactjs.org/link/error-boundaries to learn more about error boundaries.
overrideMethod @ react_devtools_backend.js:2655
logCapturedError @ bundle.js:25272
update.callback @ bundle.js:25305
callCallback @ bundle.js:17505
commitUpdateQueue @ bundle.js:17526
commitLifeCycles @ bundle.js:25923
commitLayoutEffects @ bundle.js:28613
callCallback @ bundle.js:9132
invokeGuardedCallbackDev @ bundle.js:9181
invokeGuardedCallback @ bundle.js:9243
commitRootImpl @ bundle.js:28338
unstable_runWithPriority @ bundle.js:34938
runWithPriority$1 @ bundle.js:16463
commitRoot @ bundle.js:28177
performSyncWorkOnRoot @ bundle.js:27516
(anonymous) @ bundle.js:16514
unstable_runWithPriority @ bundle.js:34938
runWithPriority$1 @ bundle.js:16463
flushSyncCallbackQueueImpl @ bundle.js:16509
flushSyncCallbackQueue @ bundle.js:16496
scheduleUpdateOnFiber @ bundle.js:27080
enqueueSetState @ bundle.js:17654
Component.setState @ bundle.js:32115
handleTextChange @ bundle.js:80370
(anonymous) @ bundle.js:94285
(anonymous) @ bundle.js:42424
fireCallbacksForOps @ bundle.js:42381
finishOperation @ bundle.js:42395
endOperation @ bundle.js:44167
runInOp @ bundle.js:44296
TextareaInput.poll @ bundle.js:49942
(anonymous) @ bundle.js:49725
bundle.js:69588 Uncaught RangeError: Maximum call stack size exceeded
Please report this to https://github.com/markedjs/marked.
    at Parser.parse (bundle.js:69588:63)
    at Object.renderer (bundle.js:94776:30)
    at Parser.parse (bundle.js:69588:63)
    at Object.renderer (bundle.js:94776:30)
    at Parser.parse (bundle.js:69588:63)
    at Object.renderer (bundle.js:94776:30)
    at Parser.parse (bundle.js:69588:63)
    at Object.renderer (bundle.js:94776:30)
    at Parser.parse (bundle.js:69588:63)
    at Object.renderer (bundle.js:94776:30)
```

**Comment by G-Ambatte** [comment]
I suspect that the `mustacheInjectInline` function is getting caught in a loop somehow, bouncing back and forth between the parser and renderer.
