### ISSUE TITLE
Issue saving document

### ISSUE THREAD

**Issue by Barren1986** [naturalcrit/homebrewery#2725]
### Error Code

```shell
Error: Service Unavailable


Error: Service Unavailable
    at Request.<anonymous> (https://homebrewery.naturalcrit.com/homebrew/bundle.js:76373:19)
    at Emitter.emit (https://homebrewery.naturalcrit.com/homebrew/bundle.js:1966:20)
    at xhr.onreadystatechange (https://homebrewery.naturalcrit.com/homebrew/bundle.js:76682:10)
{
  "status": 503,
  "method": "PUT",
  "url": "/api/update/FJQzp4zlhHxI"
}
```
```


### Your description of what happened:

I was writing a document and I had the auto-save on the document via Homebrewery but it said there was an error.

**Comment by 5e-Cleric** [comment]
This error is caused by an overflow of requests to the server, trying again after a few minutes should bring everything back to normal, was that the case?

Sorry i couldn't get to answer sooner
