### ISSUE TITLE
Error  Saving

### ISSUE THREAD

**Issue by Ekizeel** [naturalcrit/homebrewery#3007]
### Error Code

```shell
Error: Service Unavailable


Error: Service Unavailable
    at Request.<anonymous> (https://homebrewery.naturalcrit.com/homebrew/bundle.js:80465:19)
    at Emitter.emit (https://homebrewery.naturalcrit.com/homebrew/bundle.js:1966:20)
    at xhr.onreadystatechange (https://homebrewery.naturalcrit.com/homebrew/bundle.js:80774:10)
{
  "status": 503,
  "method": "PUT",
  "url": "/api/update/YLptLqyW9rQZ"
}
```
```


### Your description of what happened:

It is telling me to report the issue here, so that is what I am doing. Apparently because of an issue saving.

**Comment by 5e-Cleric** [comment]
This error has been seen when server was exceptionally busy, waiting for a few minutes should fix it for you, try again later, and comment wether the issue is still present, please.
