### ISSUE TITLE
Issue saving

### ISSUE THREAD

**Issue by elaverick** [naturalcrit/homebrewery#3050]
### Error Code

```shell
Error: Forbidden


Error: Forbidden
    at Request.<anonymous> (https://homebrewery.naturalcrit.com/homebrew/bundle.js:80465:19)
    at Emitter.emit (https://homebrewery.naturalcrit.com/homebrew/bundle.js:1966:20)
    at xhr.onreadystatechange (https://homebrewery.naturalcrit.com/homebrew/bundle.js:80774:10)
{
  "status": 403,
  "method": "PUT",
  "url": "/api/update/LUTrc4yrVNp-"
}
```
```


### Your description of what happened:

It won't let me save any of my documents. I've tried logging out of Google and back in, but it hasn't helped.

**Comment by calculuschild** [comment]
Are you signed in to the correct Google account? Google is telling us "The user does not have sufficient permissions for this file."
