### ISSUE TITLE
links to other homebrewery files precent saving

### ISSUE THREAD

**Issue by jackm105** [naturalcrit/homebrewery#3077]
### Error Code

```shell
Error: Forbidden


Error: Forbidden
    at Request.<anonymous> (https://homebrewery.naturalcrit.com/homebrew/bundle.js:80465:19)
    at Emitter.emit (https://homebrewery.naturalcrit.com/homebrew/bundle.js:1966:20)
    at xhr.onreadystatechange (https://homebrewery.naturalcrit.com/homebrew/bundle.js:80774:10)
{
  "status": 403,
  "method": "PUT",
  "url": "/api/update/CI_b8-KiR4E_"
}
```
```


### Your description of what happened:

This happens when I put any number of links into my document to other of my homebrewery files.

**Comment by calculuschild** [comment]
The error we get from Google is "The user's Drive storage quota has been exceeded." Make sure you have storage space available if you want to continue using the Google Drive storage option.
