### ISSUE TITLE
Save Error

### ISSUE THREAD

**Issue by GilleanTobin** [naturalcrit/homebrewery#3153]
### Error Code

```shell
Error: Forbidden


Error: Forbidden
    at Request.<anonymous> (https://homebrewery.naturalcrit.com/homebrew/bundle.js:80394:21)
    at Emitter.emit (https://homebrewery.naturalcrit.com/homebrew/bundle.js:1966:20)
    at XMLHttpRequest.<anonymous> (https://homebrewery.naturalcrit.com/homebrew/bundle.js:80684:10)
{
  "status": 403,
  "method": "PUT",
  "url": "/api/update/MEgIU15tsOLq"
}
```
```


### Your description of what happened:

I change a few word and when I check it didn't auto save and I can't save from that moment

**Comment by 5e-Cleric** [comment]
This issue tells us you do not have the correct permissions to edit the file, such an error could happen if you were accidentally logged out, or logged in another account, and then try to continue editing, can you be sure that is not the issue here?

**Comment by calculuschild** [comment]
@GilleanTobin Our logs say Google can't save your file because your Google Drive storage is full.
