### ISSUE TITLE
reporting a saving error - 503

### ISSUE THREAD

**Issue by Krobbolo** [naturalcrit/homebrewery#3217]
### Error Code

```shell
Error: Service Unavailable


Error: Service Unavailable
    at Request.<anonymous> (https://homebrewery.naturalcrit.com/homebrew/bundle.js:80394:21)
    at Emitter.emit (https://homebrewery.naturalcrit.com/homebrew/bundle.js:1966:20)
    at XMLHttpRequest.<anonymous> (https://homebrewery.naturalcrit.com/homebrew/bundle.js:80684:10)
{
  "status": 503,
  "method": "PUT",
  "url": "/api/update/nWt2AlWOgdfg"
}
```
```


### Your description of what happened:

the problem is happening with auto saving

**Comment by calculuschild** [comment]
Looks like our server is processing a higher load than normal right now. Try again in a couple minutes and teport back if it's still not working.

**Comment by 5e-Cleric** [comment]
We have an error page for 503, don't we?

**Comment by calculuschild** [comment]
> We have an error page for 503, don't we?

If the error occurs during saving, the message appears in a popup instead so users dont get kicked out of their work.
