### ISSUE TITLE
Issue: Saving Issue

### ISSUE THREAD

**Issue by MatRH** [naturalcrit/homebrewery#3249]
### Error Code

```shell
Error: Service Unavailable


Error: Service Unavailable
    at Request.<anonymous> (https://homebrewery.naturalcrit.com/homebrew/bundle.js:80394:21)
    at Emitter.emit (https://homebrewery.naturalcrit.com/homebrew/bundle.js:1966:20)
    at XMLHttpRequest.<anonymous> (https://homebrewery.naturalcrit.com/homebrew/bundle.js:80684:10)
{
  "status": 503,
  "method": "PUT",
  "url": "/api/update/sUT0hL111wts"
}
```
```


### Your description of what happened:

I edited a number and it failed when saving

**Comment by 5e-Cleric** [comment]
This error code tells us that the server was exceptionally busy at that time, you can wait a few minutes and it should work again.
