### ISSUE TITLE
503 issue

### ISSUE THREAD

**Issue by Rhadge** [naturalcrit/homebrewery#3302]
### Error Code

```shell
Error: Service Unavailable


Error: Service Unavailable
    at Request.<anonymous> (https://homebrewery.naturalcrit.com/homebrew/bundle.js:80394:21)
    at Emitter.emit (https://homebrewery.naturalcrit.com/homebrew/bundle.js:1966:20)
    at XMLHttpRequest.<anonymous> (https://homebrewery.naturalcrit.com/homebrew/bundle.js:80684:10)
{
  "status": 503,
  "method": "PUT",
  "url": "/api/update/pdS8Mvv_cygC"
}
```
```


### Your description of what happened:

can't save

**Comment by 5e-Cleric** [comment]
This error tells us that the server was exceptionally busy at that time, trying again in a few minutes should solve the problem.
