### ISSUE TITLE
Can't save Homebrewery File

### ISSUE THREAD

**Issue by jaspertjong** [naturalcrit/homebrewery#3310]
### Error Code

```shell
Error: Client Disconnected


Error: Client Disconnected
    at Request.<anonymous> (https://homebrewery.naturalcrit.com/homebrew/bundle.js:80394:21)
    at Emitter.emit (https://homebrewery.naturalcrit.com/homebrew/bundle.js:1966:20)
    at XMLHttpRequest.<anonymous> (https://homebrewery.naturalcrit.com/homebrew/bundle.js:80684:10)
{
  "status": 499,
  "method": "PUT",
  "url": "/api/update/k-9vOFqjjdHN"
}
```
```


### Your description of what happened:

Program gave me a warbning and directed me here.

**Comment by 5e-Cleric** [comment]
499, a client close request error, IIRC that means that either the user canceled the request(unlikely in this case) or too much traffic in the app.

I dont recall seeing any 499 errors before, so we'll keep an eye open for them, but waiting a few minutes and retrying should fix it for you.
