### ISSUE TITLE
Cannot delete co-authored brew

### ISSUE THREAD

**Issue by grimpress** [naturalcrit/homebrewery#3338]
### Error Code

```shell
Error: Internal Server Error


Error: Internal Server Error
    at Request.<anonymous> (https://homebrewery.naturalcrit.com/homebrew/bundle.js:77518:21)
    at Emitter.emit (https://homebrewery.naturalcrit.com/homebrew/bundle.js:1966:20)
    at XMLHttpRequest.<anonymous> (https://homebrewery.naturalcrit.com/homebrew/bundle.js:77808:10)
{
  "status": 500,
  "method": "DELETE",
  "url": "/api/1AVGFCz1mxoByx_NYTFp-TJhZI0CoTIDk1mnz8PaVej5s"
}
```
```


### Your description of what happened:

tried to delete unpublished brew which was shared with me, so it could be removed from my list

**Comment by 5e-Cleric** [comment]
Because this is a one time issue, that has never been reported again, i'm closing this.
