### ISSUE TITLE
The StringArrayEditor component returns error if you `ESC` out of it

### ISSUE THREAD

**Issue by Gazook89** [naturalcrit/homebrewery#3462]
### Renderer

v3

### Browser

Chrome

### Operating System

MacOS

### What happened?

The StringArrayEditor, used for the Tags input, throws an error when you hit `esc`:

```
Uncaught TypeError: Cannot set properties of undefined (setting 'editing')
    at ReactClassComponent.closeEditInput (bundle.js:80216:33)
    at ReactClassComponent.handleValueInputKeyDown (bundle.js:80211:12)
    ....
```

It is this bit:
```js
	closeEditInput : function(index) {
		const valueContext = this.state.valueContext;
		valueContext[index].editing = false;
		this.setState({ valueContext, updateValue: '' });
	},
```

**Comment by Gazook89** [comment]
I have a fix but not sure it's 100% great yet.  But at the same time, I have another question about this:

I would like to set `,` as a key used to "submit" the current tag and move to the next tag input, the same as the `Enter` key currently.  I don't think this is super controversial, but please let me know if it is.  

Further, I am wondering if `Tab` should do the same.  My reflex is that yes, `Tab` should submit the current tag and move to the next.  This would require using `Esc` to a currently non-existent container around the tags before the user could then use `Tab` again to move to the next field ("systems").  I am going to look into what specs are relevant for this kind of tag entry.   I'm also likely fine with not doing this and just leaving `Tab` as an option to move to the next field ("systems") without submitting the current tag. 

*example of tags inside another container*:
<img width="478" alt="image" src="https://github.com/naturalcrit/homebrewery/assets/58999374/23bf94a6-2ec5-4e2a-92c3-8cc12de79cc9">

Finally, i think maybe that `Tab`-ing and `Shift + Tab`-ing across the tags should activate the 'edit input' state of each tag, rather than sort of skipping them like it does now.

**Comment by Gazook89** [comment]
to go further away from original reported issue, i think the stringArrayEditor could be styled a little better to match the Homebrewery UI.  For example, get rid of the rounded corners.

**Comment by dbolack-ab** [comment]
Is this still open?

**Comment by 5e-Cleric** [comment]
Indeed, it is still a thing, #4215 details all the tag-related issues, the list is long and the component needs reworking, which is ideally happening in #3469
