### ISSUE TITLE
Error saving

### ISSUE THREAD

**Issue by FrancescoGnerre** [naturalcrit/homebrewery#3473]
### Error Code

```shell
Error: Service Unavailable


Error: Service Unavailable
    at Request.<anonymous> (https://homebrewery.naturalcrit.com/homebrew/bundle.js:77769:21)
    at Emitter.emit (https://homebrewery.naturalcrit.com/homebrew/bundle.js:1954:20)
    at XMLHttpRequest.<anonymous> (https://homebrewery.naturalcrit.com/homebrew/bundle.js:78059:10)
{
  "status": 503,
  "method": "PUT",
  "url": "/api/update/wk9AFlwtBeuP"
}
```
```


### Your description of what happened:

I saved, did about 10 minutes of work, and saved again. The second time, it took 4 attempts for it to actually save.

**Comment by 5e-Cleric** [comment]
This error tells us that the server was exceptionally busy, we recommend waiting a few minutes, then trying again.
