### ISSUE TITLE
Issue while autosaviong the document

### ISSUE THREAD

**Issue by saviopalmieri** [naturalcrit/homebrewery#3525]
### Error Code

```shell
Error: Service Unavailable


Error: Service Unavailable
    at Request.<anonymous> (https://homebrewery.naturalcrit.com/homebrew/bundle.js:77769:21)
    at Emitter.emit (https://homebrewery.naturalcrit.com/homebrew/bundle.js:1954:20)
    at XMLHttpRequest.<anonymous> (https://homebrewery.naturalcrit.com/homebrew/bundle.js:78059:10)
{
  "status": 503,
  "method": "PUT",
  "url": "/api/update/IoesZgOmqUBC"
}
```
```


### Your description of what happened:

An alert appeared and no save action was possible

**Comment by 5e-Cleric** [comment]
This error tells us that the server was exceptionally busy, we recommend waiting a few minutes, then trying again.
