### ISSUE TITLE
Saving Error

### ISSUE THREAD

**Issue by EthanSausville** [naturalcrit/homebrewery#3601]
### Error Code

```shell
Error: Service Unavailable


Error: Service Unavailable
    at Request.<anonymous> (https://homebrewery.naturalcrit.com/homebrew/bundle.js:78344:21)
    at Emitter.emit (https://homebrewery.naturalcrit.com/homebrew/bundle.js:1954:20)
    at XMLHttpRequest.<anonymous> (https://homebrewery.naturalcrit.com/homebrew/bundle.js:78638:10)
{
  "status": 503,
  "method": "PUT",
  "url": "/api/update/SMV2gx_6E6wB"
}
```
```


### Your description of what happened:

There was an error with saving the file. It keeps thinking changes have been made on another device, but that is not the case.

**Comment by 5e-Cleric** [comment]
This error tells us that the server was exceptionally busy, we recommend waiting a few minutes, then trying again.
