### ISSUE TITLE
Server times out if trying to access `/account` while not logged in

### ISSUE THREAD

**Issue by calculuschild** [naturalcrit/homebrewery#3605]
We need to check if a user is logged in and handle the case if not.

```
2024-07-31T20:11:05.320603+00:00 app[web.1]: TypeError: Cannot read properties of undefined (reading 'username')
2024-07-31T20:11:05.320614+00:00 app[web.1]:     at renderAccountPage (/app/build/homebrew/ssr.js:3009:133)
2024-07-31T20:11:05.320614+00:00 app[web.1]:     at AccountPage (/app/build/homebrew/ssr.js:3025:6)
2024-07-31T20:11:05.320615+00:00 app[web.1]:     at Fb (/app/node_modules/react-dom/cjs/react-dom-server-legacy.node.production.min.js:65:44)
2024-07-31T20:11:05.320615+00:00 app[web.1]:     at Ib (/app/node_modules/react-dom/cjs/react-dom-server-legacy.node.production.min.js:67:254)
2024-07-31T20:11:05.320616+00:00 app[web.1]:     at W (/app/node_modules/react-dom/cjs/react-dom-server-legacy.node.production.min.js:73:89)
2024-07-31T20:11:05.320616+00:00 app[web.1]:     at Ib (/app/node_modules/react-dom/cjs/react-dom-server-legacy.node.production.min.js:67:482)
2024-07-31T20:11:05.320616+00:00 app[web.1]:     at W (/app/node_modules/react-dom/cjs/react-dom-server-legacy.node.production.min.js:73:89)
2024-07-31T20:11:05.320617+00:00 app[web.1]:     at Ib (/app/node_modules/react-dom/cjs/react-dom-server-legacy.node.production.min.js:71:304)
2024-07-31T20:11:05.320617+00:00 app[web.1]:     at W (/app/node_modules/react-dom/cjs/react-dom-server-legacy.node.production.min.js:73:89)
2024-07-31T20:11:05.320617+00:00 app[web.1]:     at Ib (/app/node_modules/react-dom/cjs/react-dom-server-legacy.node.production.min.js:67:482)
2024-07-31T20:11:06.496145+00:00 app[web.1]: TypeError: Cannot read properties of undefined (reading 'username')
2024-07-31T20:11:06.496170+00:00 app[web.1]:     at renderAccountPage (/app/build/homebrew/ssr.js:3009:133)
2024-07-31T20:11:06.496170+00:00 app[web.1]:     at AccountPage (/app/build/homebrew/ssr.js:3025:6)
2024-07-31T20:11:06.496171+00:00 app[web.1]:     at Fb (/app/node_modules/react-dom/cjs/react-dom-server-legacy.node.production.min.js:65:44)
2024-07-31T20:11:06.496171+00:00 app[web.1]:     at Ib (/app/node_modules/react-dom/cjs/react-dom-server-legacy.node.production.min.js:67:254)
2024-07-31T20:11:06.496172+00:00 app[web.1]:     at W (/app/node_modules/react-dom/cjs/react-dom-server-legacy.node.production.min.js:73:89)
2024-07-31T20:11:06.496173+00:00 app[web.1]:     at Ib (/app/node_modules/react-dom/cjs/react-dom-server-legacy.node.production.min.js:67:482)
2024-07-31T20:11:06.496173+00:00 app[web.1]:     at W (/app/node_modules/react-dom/cjs/react-dom-server-legacy.node.production.min.js:73:89)
2024-07-31T20:11:06.496173+00:00 app[web.1]:     at Ib (/app/node_modules/react-dom/cjs/react-dom-server-legacy.node.production.min.js:71:304)
2024-07-31T20:11:06.496173+00:00 app[web.1]:     at W (/app/node_modules/react-dom/cjs/react-dom-server-legacy.node.production.min.js:73:89)
2024-07-31T20:11:06.496174+00:00 app[web.1]:     at Ib (/app/node_modules/react-dom/cjs/react-dom-server-legacy.node.production.min.js:67:482)
```

**Comment by 5e-Cleric** [comment]
Hmm, good catch. it should probably redirect to a new brew or to the login if the user is not logged in.

**Comment by 5e-Cleric** [comment]
But is it P0? no data is lost, 99% of users won't be able to get into the page while not logged in.

**Comment by calculuschild** [comment]
It crashes the whole server, which means the site is down for everyone.

**Comment by 5e-Cleric** [comment]
Ah, must admit i tried the moment i saw the title.
