### ISSUE TITLE
Non-used URLs open bugged new page

### ISSUE THREAD

**Issue by 5e-Cleric** [naturalcrit/homebrewery#3629]
Any URL that is not defined in our router by default opens a `/new` page. However after the custom themes update (v3.14.0), this opens with errors in saving and no snippet menus:

![image](https://github.com/user-attachments/assets/9eaaf73b-c083-488f-9354-12b8e35a1ed3)

With the next error in console:

```
Error: Not Found
    at Request.<anonymous> (https://homebrewery.naturalcrit.com/homebrew/bundle.js:78344:21)
    at Emitter.emit (https://homebrewery.naturalcrit.com/homebrew/bundle.js:1954:20)
    at XMLHttpRequest.<anonymous> (https://homebrewery.naturalcrit.com/homebrew/bundle.js:78638:10)
{
  "status": 404,
  "method": "GET",
  "url": "/api/theme/undefined/undefined"
}
```

This should be fixed.

**Comment by 5e-Cleric** [comment]
Hmm, yeah, alright then.
