### ISSUE TITLE
Saving Error

### ISSUE THREAD

**Issue by DaLeLN** [naturalcrit/homebrewery#3747]
### Error Code

```shell
Error: Too Many Requests


Error: Too Many Requests
    at Request.<anonymous> (https://homebrewery.naturalcrit.com/homebrew/bundle.js:78380:21)
    at Emitter.emit (https://homebrewery.naturalcrit.com/homebrew/bundle.js:1954:20)
    at XMLHttpRequest.<anonymous> (https://homebrewery.naturalcrit.com/homebrew/bundle.js:78674:10)
{
  "status": 429,
  "method": "PUT",
  "url": "/api/update/JnAJDKspCHdf"
}
```
```


### Your description of what happened:

I was just changing a text and the error happened

**Comment by Gazook89** [comment]
It's being looked at, thanks for the report.  Will update you once it's fixed

**Comment by Gazook89** [comment]
This problem should be resolved now.  If it persists for you, [please followup in this thread](https://github.com/naturalcrit/homebrewery/issues/3746).

Closing this comment as a duplicate.
