### ISSUE TITLE
Saving Error on Naturalcrit.com

### ISSUE THREAD

**Issue by Alarion2416** [naturalcrit/homebrewery#3748]
### Error Code

```shell
Error: Unauthorized


Error: Unauthorized
    at Request.<anonymous> (https://homebrewery.naturalcrit.com/homebrew/bundle.js:78380:21)
    at Emitter.emit (https://homebrewery.naturalcrit.com/homebrew/bundle.js:1954:20)
    at XMLHttpRequest.<anonymous> (https://homebrewery.naturalcrit.com/homebrew/bundle.js:78674:10)
{
  "status": 401,
  "method": "PUT",
  "url": "/api/update/xOD4GcItrCAA"
}
```
```


### Your description of what happened:

The Error just occured.

**Comment by Gazook89** [comment]
This problem should be resolved now.  If it persists for you, [please followup in this thread](https://github.com/naturalcrit/homebrewery/issues/3746).

Closing this comment as a duplicate.
