### ISSUE TITLE
Too many requests

### ISSUE THREAD

**Issue by dangerdesign** [naturalcrit/homebrewery#3751]
### Error Code

```shell
Error: Too Many Requests


Error: Too Many Requests
    at Request.<anonymous> (https://homebrewery.naturalcrit.com/homebrew/bundle.js:78380:21)
    at Emitter.emit (https://homebrewery.naturalcrit.com/homebrew/bundle.js:1954:20)
    at XMLHttpRequest.<anonymous> (https://homebrewery.naturalcrit.com/homebrew/bundle.js:78674:10)
{
  "status": 429,
  "method": "PUT",
  "url": "/api/update/9kN9scqQYUyj"
}
```
```


### Your description of what happened:

I saw a new popup, so I clicked it

Hello, world!

**Comment by 5e-Cleric** [comment]
It's being looked at, thanks for the report. Will update you once it's fixed.

**Comment by Gazook89** [comment]
This problem should be resolved now.  If it persists for you, [please followup in this thread](https://github.com/naturalcrit/homebrewery/issues/3746).

Closing this comment as a duplicate.
