### ISSUE TITLE
Problem Saving

### ISSUE THREAD

**Issue by SamHain-1031** [naturalcrit/homebrewery#3756]
### Error Code

```shell
Error: Too Many Requests


Error: Too Many Requests
    at Request.<anonymous> (https://homebrewery.naturalcrit.com/homebrew/bundle.js:78380:21)
    at Emitter.emit (https://homebrewery.naturalcrit.com/homebrew/bundle.js:1954:20)
    at XMLHttpRequest.<anonymous> (https://homebrewery.naturalcrit.com/homebrew/bundle.js:78674:10)
{
  "status": 429,
  "method": "PUT",
  "url": "/api/update/5rhqmPfcMK7o"
}
```
```


### Your description of what happened:

Just made a quick spelling correction.  Found that manual and auto-saving isn't functioning across multiple homebrews (all that I've tried so far).

**Comment by Gazook89** [comment]
This problem should be resolved now.  If it persists for you, [please followup in this thread](https://github.com/naturalcrit/homebrewery/issues/3746).

Closing this comment as a duplicate.
