### ISSUE TITLE
Error on saving several documents

### ISSUE THREAD

**Issue by macargo07** [naturalcrit/homebrewery#3759]
### Error Code

```shell
Error: Too Many Requests


Error: Too Many Requests
    at Request.<anonymous> (https://homebrewery.naturalcrit.com/homebrew/bundle.js:78380:21)
    at Emitter.emit (https://homebrewery.naturalcrit.com/homebrew/bundle.js:1954:20)
    at XMLHttpRequest.<anonymous> (https://homebrewery.naturalcrit.com/homebrew/bundle.js:78674:10)
{
  "status": 429,
  "method": "PUT",
  "url": "/api/update/73ze3M4H2I93"
}
```
```


### Your description of what happened:

In two of my documents i have an issue with the autosaving and the manual saving.

**Comment by Gazook89** [comment]
This problem should be resolved now.  If it persists for you, [please followup in this thread](https://github.com/naturalcrit/homebrewery/issues/3746).

Closing this comment as a duplicate.
