### ISSUE TITLE
Unknown saving issue

### ISSUE THREAD

**Issue by CJMolten** [naturalcrit/homebrewery#3768]
### Error Code

```shell
Error: Too Many Requests


Error: Too Many Requests
    at Request.<anonymous> (https://homebrewery.naturalcrit.com/homebrew/bundle.js:78380:21)
    at Emitter.emit (https://homebrewery.naturalcrit.com/homebrew/bundle.js:1954:20)
    at XMLHttpRequest.<anonymous> (https://homebrewery.naturalcrit.com/homebrew/bundle.js:78674:10)
{
  "status": 429,
  "method": "PUT",
  "url": "/api/update/W_v2-WaIT3BZ"
}
```
```


### Your description of what happened:

 I've had trouble saving my documents in general with the prompt that the document has been saved on another device. This is the first time I have encountered this specific issue however. 
- Thanks

**Comment by G-Ambatte** [comment]
Merging to mega-issue #3770.
