### ISSUE TITLE
issue Saving

### ISSUE THREAD

**Issue by MattPM1311** [naturalcrit/homebrewery#3769]
### Error Code

```shell
Error: Too Many Requests


Error: Too Many Requests
    at Request.<anonymous> (https://homebrewery.naturalcrit.com/homebrew/bundle.js:78380:21)
    at Emitter.emit (https://homebrewery.naturalcrit.com/homebrew/bundle.js:1954:20)
    at XMLHttpRequest.<anonymous> (https://homebrewery.naturalcrit.com/homebrew/bundle.js:78674:10)
{
  "status": 429,
  "method": "PUT",
  "url": "/api/update/T8E1pB7gcxFl"
}
```
```


### Your description of what happened:

got this error again

**Comment by G-Ambatte** [comment]
Merging to mega-issue #3770.
