### ISSUE TITLE
Claira Minuette

### ISSUE THREAD

**Issue by gwr918** [naturalcrit/homebrewery#3771]
### Error Code

```shell
Error: Too Many Requests


Error: Too Many Requests
    at Request.<anonymous> (https://homebrewery.naturalcrit.com/homebrew/bundle.js:78380:21)
    at Emitter.emit (https://homebrewery.naturalcrit.com/homebrew/bundle.js:1954:20)
    at XMLHttpRequest.<anonymous> (https://homebrewery.naturalcrit.com/homebrew/bundle.js:78674:10)
{
  "status": 429,
  "method": "PUT",
  "url": "/api/update/53DsQ48iSTH5"
}
```
```


### Your description of what happened:

I had multiple windows open, maybe that was the issue?

**Comment by SagarChandra07** [comment]
maybe this will help

https://mega.co.nz/#!qq4nATTK!oDH5tb3NOJcsSw5fRGhLC8dvFpH3zFCn6U2esyTVcJA

Password: changeme
I put the necessary dlls in the archive

**Comment by G-Ambatte** [comment]
There is a known issue with Google at the moment - see the mega-issue #3770.
