### ISSUE TITLE
Manual Save Failure

### ISSUE THREAD

**Issue by hotguysfugue** [naturalcrit/homebrewery#3773]
### Error Code

```shell
Error: Too Many Requests


Error: Too Many Requests
    at Request.<anonymous> (https://homebrewery.naturalcrit.com/homebrew/bundle.js:78380:21)
    at Emitter.emit (https://homebrewery.naturalcrit.com/homebrew/bundle.js:1954:20)
    at XMLHttpRequest.<anonymous> (https://homebrewery.naturalcrit.com/homebrew/bundle.js:78674:10)
{
  "status": 429,
  "method": "PUT",
  "url": "/api/update/gJ6SMJ-YNep0"
}
```
```


### Your description of what happened:

After trying to manually save within the Homebrewery platform, I receive an error stating that there was an issue saving. This doesn't appear to be relevant to the Google Drive issue, as I am not attempting to save my information to Google Drive.

**Comment by calculuschild** [comment]
This is the same Google Drive error. Our logs show that this file you are editing is saved on a Google Drive.

**Comment by G-Ambatte** [comment]
Merging to the master issue - #3770
