### ISSUE TITLE
Can't save

### ISSUE THREAD

**Issue by RangerTyr** [naturalcrit/homebrewery#3774]
### Error Code

```shell
Error: Too Many Requests


Error: Too Many Requests
    at Request.<anonymous> (https://homebrewery.naturalcrit.com/homebrew/bundle.js:78380:21)
    at Emitter.emit (https://homebrewery.naturalcrit.com/homebrew/bundle.js:1954:20)
    at XMLHttpRequest.<anonymous> (https://homebrewery.naturalcrit.com/homebrew/bundle.js:78674:10)
{
  "status": 429,
  "method": "PUT",
  "url": "/api/update/oYue2GCMBXyA"
}
```
```


### Your description of what happened:

Have not been able to save.

**Comment by G-Ambatte** [comment]
This is a known issue - see Master issue at #3770.
