### ISSUE TITLE
Unable to save

### ISSUE THREAD

**Issue by graysonithaca** [naturalcrit/homebrewery#3775]
### Error Code

```shell
Error: Too Many Requests


Error: Too Many Requests
    at Request.<anonymous> (https://homebrewery.naturalcrit.com/homebrew/bundle.js:78380:21)
    at Emitter.emit (https://homebrewery.naturalcrit.com/homebrew/bundle.js:1954:20)
    at XMLHttpRequest.<anonymous> (https://homebrewery.naturalcrit.com/homebrew/bundle.js:78674:10)
{
  "status": 429,
  "method": "PUT",
  "url": "/api/update/j_ZaG3w-6A_T"
}
```
```


### Your description of what happened:

Every time I submit to save whatever I have done on the page, it would appear with an error.

**Comment by G-Ambatte** [comment]
This is a known issue - see the Master issue #3770.
