### ISSUE TITLE
Auto and manual save issue.

### ISSUE THREAD

**Issue by VuelBlackberry** [naturalcrit/homebrewery#3777]
### Error Code

```shell
Error: Too Many Requests


Error: Too Many Requests
    at Request.<anonymous> (https://homebrewery.naturalcrit.com/homebrew/bundle.js:78380:21)
    at Emitter.emit (https://homebrewery.naturalcrit.com/homebrew/bundle.js:1954:20)
    at XMLHttpRequest.<anonymous> (https://homebrewery.naturalcrit.com/homebrew/bundle.js:78674:10)
{
  "status": 429,
  "method": "PUT",
  "url": "/api/update/7F6pQYYnTMzM"
}
```
```


### Your description of what happened:

Every time I try save it only times me it fails to save no matter if I let it do it automatically or manually.
![image](https://github.com/user-attachments/assets/6645915f-174c-49e2-87c5-ec5d345f530b)

**Comment by 5e-Cleric** [comment]
This is a known issue - see the Master issue #3770.
