### ISSUE TITLE
does not save

### ISSUE THREAD

**Issue by Lopex-23** [naturalcrit/homebrewery#3780]
### Error Code

```shell
Error: Unauthorized


Error: Unauthorized
    at Request.<anonymous> (https://homebrewery.naturalcrit.com/homebrew/bundle.js:78380:21)
    at Emitter.emit (https://homebrewery.naturalcrit.com/homebrew/bundle.js:1954:20)
    at XMLHttpRequest.<anonymous> (https://homebrewery.naturalcrit.com/homebrew/bundle.js:78674:10)
{
  "status": 401,
  "method": "PUT",
  "url": "/api/update/k6M_h_A4ByQE"
}
```
```


### Your description of what happened:

the system is not saving when I modify the pages, neither automatically nor manually

**Comment by 5e-Cleric** [comment]
This is a known issue - see the Master issue #3770.
