### ISSUE TITLE
Saving not possible

### ISSUE THREAD

**Issue by Andor90** [naturalcrit/homebrewery#3782]
### Error Code

```shell
Error: Unauthorized


Error: Unauthorized
    at Request.<anonymous> (https://homebrewery.naturalcrit.com/homebrew/bundle.js:78380:21)
    at Emitter.emit (https://homebrewery.naturalcrit.com/homebrew/bundle.js:1954:20)
    at XMLHttpRequest.<anonymous> (https://homebrewery.naturalcrit.com/homebrew/bundle.js:78674:10)
{
  "status": 401,
  "method": "PUT",
  "url": "/api/update/DdTxNO4gMjzA"
}
```
```


### Your description of what happened:

I cannot save my Homebrewery.

**Comment by 5e-Cleric** [comment]
This is a known issue - see the Master issue #3770.
