### ISSUE TITLE
Another Saving Error

### ISSUE THREAD

**Issue by GamerWorthyStudios** [naturalcrit/homebrewery#3791]
### Error Code

```shell
Error: Too Many Requests


Error: Too Many Requests
    at Request.<anonymous> (https://homebrewery.naturalcrit.com/homebrew/bundle.js:78380:21)
    at Emitter.emit (https://homebrewery.naturalcrit.com/homebrew/bundle.js:1954:20)
    at XMLHttpRequest.<anonymous> (https://homebrewery.naturalcrit.com/homebrew/bundle.js:78674:10)
{
  "status": 429,
  "method": "PUT",
  "url": "/api/update/pg5H0uVJx7UW"
}
```
```


### Your description of what happened:

Inability to save.

**Comment by 5e-Cleric** [comment]
This is a known issue - see Master issue at #3770.
