### ISSUE TITLE
cant delete HB file

### ISSUE THREAD

**Issue by grimpress** [naturalcrit/homebrewery#3872]
### Error Code

```shell
Error: Internal Server Error


Error: Internal Server Error
    at Request.<anonymous> (https://homebrewery.naturalcrit.com/homebrew/bundle.js:78451:21)
    at Emitter.emit (https://homebrewery.naturalcrit.com/homebrew/bundle.js:1954:20)
    at XMLHttpRequest.<anonymous> (https://homebrewery.naturalcrit.com/homebrew/bundle.js:78745:10)
{
  "status": 500,
  "method": "DELETE",
  "url": "/api/13vTgCjTjR9Vp4ZtkddqK22S5_zBzowDCdkbpljc-C69K"
}
```
```


### Your description of what happened:

saved a backup and then tried to delete brew.

Would be nice to just have an "archive" button to get them off our main HB page. Or maybe make folders so we can organize our brews instead of just a massive list of items

**Comment by 5e-Cleric** [comment]
This could very well be a one time issue, if it can be reproduced, we will keep it open.

**Comment by calculuschild** [comment]
I suspect this is related to https://github.com/naturalcrit/homebrewery/issues/2954

**Comment by calculuschild** [comment]
I believe so, yes. @grimpress if you are able, can you please try to delete this file again?
