### ISSUE TITLE
File saving failure 

### ISSUE THREAD

**Issue by Tommy9llo** [naturalcrit/homebrewery#3875]
### Error Code

```shell
Error: Too Many Requests


Error: Too Many Requests
    at Request.<anonymous> (https://homebrewery.naturalcrit.com/homebrew/bundle.js:78451:21)
    at Emitter.emit (https://homebrewery.naturalcrit.com/homebrew/bundle.js:1954:20)
    at XMLHttpRequest.<anonymous> (https://homebrewery.naturalcrit.com/homebrew/bundle.js:78745:10)
{
  "status": 429,
  "method": "PUT",
  "url": "/api/update/HTXpcSuLd9n3"
}
```
```


### Your description of what happened:

While I was writing on my homebrew file, the save stopped working, I tried to restart but the problem still persists.

**Comment by 5e-Cleric** [comment]
Closing in favor of #3770
