### ISSUE TITLE
Issue Saving

### ISSUE THREAD

**Issue by j1ng3rs0ll** [naturalcrit/homebrewery#3876]
### Error Code

```shell
Error: Too Many Requests


Error: Too Many Requests
    at Request.<anonymous> (https://homebrewery.naturalcrit.com/homebrew/bundle.js:78451:21)
    at Emitter.emit (https://homebrewery.naturalcrit.com/homebrew/bundle.js:1954:20)
    at XMLHttpRequest.<anonymous> (https://homebrewery.naturalcrit.com/homebrew/bundle.js:78745:10)
{
  "status": 429,
  "method": "PUT",
  "url": "/api/update/KADFk2ozeWPf"
}
```
```


### Your description of what happened:

I was told there was an issue saving but not much else.

**Comment by 5e-Cleric** [comment]
Closing in favor of #3770

**Comment by j1ng3rs0ll** [comment]
What's going on?
