### ISSUE TITLE
Homebrewery appears to be rate limited by Google Drive?

### ISSUE THREAD

**Issue by DavidTurk** [naturalcrit/homebrewery#3877]
### Error Code

```shell
Error: Too Many Requests


Error: Too Many Requests
    at Request.<anonymous> (https://homebrewery.naturalcrit.com/homebrew/bundle.js:78451:21)
    at Emitter.emit (https://homebrewery.naturalcrit.com/homebrew/bundle.js:1954:20)
    at XMLHttpRequest.<anonymous> (https://homebrewery.naturalcrit.com/homebrew/bundle.js:78745:10)
{
  "status": 429,
  "method": "PUT",
  "url": "/api/update/2FJj8CC7g82x"
}
```
```


### Your description of what happened:

All saving is erroring, auto-save or not.
![image](https://github.com/user-attachments/assets/75cbce35-ce7b-48e2-99fa-7e4b18b59944)

**Comment by calculuschild** [comment]
See #3770
