### ISSUE TITLE
Issue saving to Google Docs

### ISSUE THREAD

**Issue by DukeSammael** [naturalcrit/homebrewery#3878]
### Error Code

```shell
Error: Too Many Requests


Error: Too Many Requests
    at Request.<anonymous> (https://homebrewery.naturalcrit.com/homebrew/bundle.js:78451:21)
    at Emitter.emit (https://homebrewery.naturalcrit.com/homebrew/bundle.js:1954:20)
    at XMLHttpRequest.<anonymous> (https://homebrewery.naturalcrit.com/homebrew/bundle.js:78745:10)
{
  "status": 429,
  "method": "PUT",
  "url": "/api/update/ByjLXh78V2Ef"
}
```
```


### Your description of what happened:

Tried working on the brew that I opened, edited, and saved normally 8 hours ago, and I'm now getting an error when saving to Google Docs. Copying content and saving to Homebrewery works normal.

**Comment by calculuschild** [comment]
See https://github.com/naturalcrit/homebrewery/issues/3770
