### ISSUE TITLE
Issue saving to G Drive

### ISSUE THREAD

**Issue by infinitewh1sper** [naturalcrit/homebrewery#3879]
### Error Code

```shell
Error: Too Many Requests


Error: Too Many Requests
    at Request.<anonymous> (https://homebrewery.naturalcrit.com/homebrew/bundle.js:78451:21)
    at Emitter.emit (https://homebrewery.naturalcrit.com/homebrew/bundle.js:1954:20)
    at XMLHttpRequest.<anonymous> (https://homebrewery.naturalcrit.com/homebrew/bundle.js:78745:10)
{
  "status": 429,
  "method": "PUT",
  "url": "/api/update/1YOsvAiNKl3B"
}
```
```


### Your description of what happened:

The file had trouble saving to G Drive. All my other docs work fine, this one doesn't. I even lost more than 5 pages of works thinking it was saved to find out it didn't.

**Comment by calculuschild** [comment]
See https://github.com/naturalcrit/homebrewery/issues/3770
